import { createHmac, timingSafeEqual } from "node:crypto";
import { NextResponse, type NextRequest } from "next/server";
import { Resend } from "resend";
import { render } from "@react-email/components";
import { SignInCodeEmail } from "@/emails/canes/signin-code-email";

// Supabase Send Email Hook — WE send the auth emails, not Supabase.
//
// Supabase's built-in mailer is throttled to a couple of messages an hour. That
// is survivable for one developer and useless the moment a crew all clock in at
// 7am, and it also sends from a supabase.io address with none of the Canes
// branding. This hook takes the whole thing over: Supabase POSTs the generated
// code here, and we deliver it through the same Resend account and the same
// react-email shell as every estimate and invoice.
//
// Setup (Authentication → Hooks → Send Email):
//   URL     https://urso.ws/api/canes/auth/email-hook
//   Secret  generated by Supabase, stored as CANES_AUTH_HOOK_SECRET
//
// SECURITY: this endpoint is public and hands out nothing, but anyone who could
// forge a call to it could make us send arbitrary mail from urso.ws. Every
// request is signature-verified and fails closed.

export const dynamic = "force-dynamic";

// standard-webhooks: sign `{id}.{timestamp}.{body}` with the base64-decoded
// secret, compare against any `v1,<sig>` entry in the webhook-signature header.
// Implemented here rather than pulling the package in — the same hand-rolled
// HMAC pattern lib/urso-auth.ts and the Square webhook already use, and it
// keeps a transitive dependency out of the trust path.
const TOLERANCE_SECONDS = 5 * 60;

function verify(body: string, headers: Headers, secret: string): boolean {
  const id = headers.get("webhook-id");
  const timestamp = headers.get("webhook-timestamp");
  const signature = headers.get("webhook-signature");
  if (!id || !timestamp || !signature) return false;

  // Reject stale requests so a captured call can't be replayed later.
  const sent = Number(timestamp);
  if (!Number.isFinite(sent)) return false;
  if (Math.abs(Math.floor(Date.now() / 1000) - sent) > TOLERANCE_SECONDS) return false;

  // Supabase stores the secret as "v1,whsec_<base64>"; the signing key is the
  // decoded bytes after that prefix.
  const raw = secret.replace(/^v1,/, "").replace(/^whsec_/, "");
  let key: Buffer;
  try {
    key = Buffer.from(raw, "base64");
  } catch {
    return false;
  }

  const expected = createHmac("sha256", key).update(`${id}.${timestamp}.${body}`).digest("base64");
  const expectedBuf = Buffer.from(expected);

  // The header may carry several space-delimited versioned signatures.
  for (const part of signature.split(" ")) {
    const [version, value] = part.split(",");
    if (version !== "v1" || !value) continue;
    const candidate = Buffer.from(value);
    if (candidate.length === expectedBuf.length && timingSafeEqual(candidate, expectedBuf)) {
      return true;
    }
  }
  return false;
}

type HookPayload = {
  user?: { email?: string };
  email_data?: { token?: string; email_action_type?: string };
};

export async function POST(req: NextRequest): Promise<NextResponse> {
  const secret = process.env.CANES_AUTH_HOOK_SECRET;
  const apiKey = process.env.RESEND_API; // note: RESEND_API, not RESEND_API_KEY
  if (!secret || !apiKey) {
    console.error("[canes auth hook] CANES_AUTH_HOOK_SECRET or RESEND_API is not set");
    // 500 so Supabase surfaces the failure instead of silently sending nothing.
    return NextResponse.json({ error: "not configured" }, { status: 500 });
  }

  const body = await req.text();
  if (!verify(body, req.headers, secret)) {
    return NextResponse.json({ error: "invalid signature" }, { status: 401 });
  }

  let payload: HookPayload;
  try {
    payload = JSON.parse(body) as HookPayload;
  } catch {
    return NextResponse.json({ error: "invalid payload" }, { status: 400 });
  }

  const to = payload.user?.email;
  const code = payload.email_data?.token;
  if (!to || !code) {
    return NextResponse.json({ error: "missing email or token" }, { status: 400 });
  }

  // signInWithOtp on an existing account arrives as "magiclink"; the crew flow
  // is allowlist-only (shouldCreateUser: false) so "signup" should not occur,
  // but handle it rather than mislabel the copy if it ever does.
  const action = payload.email_data?.email_action_type === "signup" ? "signup" : "login";

  const html = await render(SignInCodeEmail({ code, action }));

  try {
    const resend = new Resend(apiKey);
    const { error } = await resend.emails.send({
      from: process.env.CANES_AUTH_EMAIL_FROM ?? "Canes Pressure Washing <server@urso.ws>",
      to: [to],
      subject: "Your Canes sign-in code",
      html,
    });
    if (error) {
      const message = typeof error === "string" ? error : error.message;
      // Never log `code` — this line ends up in a shared log.
      console.error(`[canes auth hook] resend failed for ${to}: ${message}`);
      // Non-200 tells Supabase the send failed, so the user sees an error
      // instead of waiting for an email that will never arrive.
      return NextResponse.json({ error: "send failed" }, { status: 502 });
    }
  } catch (e) {
    console.error(`[canes auth hook] threw: ${e instanceof Error ? e.message : String(e)}`);
    return NextResponse.json({ error: "send failed" }, { status: 502 });
  }

  // Supabase treats an empty 200 as success.
  return NextResponse.json({}, { status: 200 });
}
