import type {
  ActivityEvent,
  Artifact,
  Discipline,
  RolePersona,
  WorkflowStep,
} from "./types";

export const project = {
  id: "uberlandia-refrescos-f3",
  name: "Uberlândia Refrescos",
  phase: "Fase 3",
  stage: "Projeto executivo",
  location: "Uberlândia, MG",
  nextMilestone: "Liberação do projeto executivo",
  baselineDays: 14,
  publicFacts: "49.350 m² · 80.000 garrafas/hora · expansão industrial",
} as const;

export const disciplines: Discipline[] = [
  {
    id: "viability",
    name: "Viabilidade",
    englishName: "Viability",
    shortName: "VIA",
    group: "brain",
    impact: "none",
    impactSummary: "Nenhuma alteração de viabilidade confirmada nesta etapa.",
    workItem: "Registrar efeito sobre a premissa de capacidade da linha.",
    owner: "Líder de Viabilidade",
  },
  {
    id: "bid",
    name: "BID",
    englishName: "BID",
    shortName: "BID",
    group: "brain",
    impact: "none",
    impactSummary: "Nenhum efeito contratual confirmado nesta etapa.",
    workItem: "Monitorar impacto comercial caso a recuperação altere escopo ou custo.",
    owner: "Coordenador de BID",
  },
  {
    id: "planning",
    name: "Planejamento e Controle",
    englishName: "Planning & Control",
    shortName: "PLA",
    group: "brain",
    impact: "critical",
    impactSummary: "Atraso de 10 dias ameaça o marco de liberação executiva.",
    workItem: "Comparar três opções de recuperação e recalcular o caminho crítico.",
    owner: "Engenheiro de Planejamento",
  },
  {
    id: "quality",
    name: "Qualidade",
    englishName: "Quality",
    shortName: "QUA",
    group: "brain",
    impact: "watch",
    impactSummary: "O gate exige evidência de revisão das disciplinas afetadas.",
    workItem: "Atualizar checklist e bloquear liberação até seis aprovações.",
    owner: "Líder de Qualidade",
  },
  {
    id: "bim",
    name: "Metodologia BIM",
    englishName: "BIM Methodology",
    shortName: "BIM",
    group: "brain",
    impact: "critical",
    impactSummary: "Footprint e pontos de conexão exigem nova coordenação federada.",
    workItem: "Gerar scaffold conceitual e executar verificação de interferências.",
    owner: "Coordenador BIM",
  },
  {
    id: "architecture",
    name: "Arquitetura",
    englishName: "Architecture",
    shortName: "ARQ",
    group: "skeleton",
    impact: "support",
    impactSummary: "O novo envelope reduz a faixa de circulação adjacente.",
    workItem: "Revalidar circulação, acessos e zonas de manutenção.",
    owner: "Líder de Arquitetura",
  },
  {
    id: "infrastructure",
    name: "Infraestrutura",
    englishName: "Infrastructure",
    shortName: "INF",
    group: "skeleton",
    impact: "none",
    impactSummary: "Rotas externas permanecem estáveis nesta revisão.",
    workItem: "Validar interface da rede externa com o novo ponto de entrada.",
    owner: "Líder de Infraestrutura",
  },
  {
    id: "concrete",
    name: "Estruturas de Concreto",
    englishName: "Concrete Structures",
    shortName: "CON",
    group: "skeleton",
    impact: "critical",
    impactSummary: "Base do equipamento depende da nova geometria e carga confirmada.",
    workItem: "Recalcular bloco de fundação e emitir marcação de revisão.",
    owner: "Engenheiro Estrutural",
  },
  {
    id: "steel",
    name: "Estruturas Metálicas",
    englishName: "Steel Structures",
    shortName: "MET",
    group: "skeleton",
    impact: "none",
    impactSummary: "Nenhum suporte metálico afetado foi identificado.",
    workItem: "Confirmar necessidade de ajuste em suportes secundários.",
    owner: "Líder de Estruturas Metálicas",
  },
  {
    id: "hydraulics",
    name: "Hidráulica",
    englishName: "Hydraulics",
    shortName: "HID",
    group: "organs",
    impact: "none",
    impactSummary: "Sem alteração de consumo sanitário ou drenagem confirmada.",
    workItem: "Revalidar interferência da drenagem de piso.",
    owner: "Líder de Hidráulica",
  },
  {
    id: "hvac",
    name: "HVAC",
    englishName: "HVAC",
    shortName: "HVA",
    group: "organs",
    impact: "critical",
    impactSummary: "Demanda de água gelada aumentou 18%.",
    workItem: "Atualizar balanço térmico, vazão e conexão da linha.",
    owner: "Líder de HVAC",
  },
  {
    id: "electrical",
    name: "Elétrica",
    englishName: "Electrical",
    shortName: "ELE",
    group: "organs",
    impact: "critical",
    impactSummary: "Carga instalada da linha aumentou 15%.",
    workItem: "Atualizar lista de cargas, alimentador e diagrama unifilar.",
    owner: "Líder de Elétrica",
  },
  {
    id: "mechanical",
    name: "Mecânica e Tubulação",
    englishName: "Mechanical & Piping",
    shortName: "MEC",
    group: "organs",
    impact: "watch",
    impactSummary: "Conexões e rotas devem acompanhar o deslocamento de 1,2 m.",
    workItem: "Revisar tie-ins, suportação e lista de linhas.",
    owner: "Líder de Mecânica",
  },
  {
    id: "automation",
    name: "Sistemas Especiais e Automação",
    englishName: "Special Systems & Automation",
    shortName: "AUT",
    group: "organs",
    impact: "watch",
    impactSummary: "A nova revisão pode alterar pontos de I/O e intertravamentos.",
    workItem: "Comparar lista de I/O e atualizar matriz de causa e efeito.",
    owner: "Líder de Automação",
  },
  {
    id: "fire",
    name: "Proteção Contra Incêndio",
    englishName: "Fire Protection",
    shortName: "PCI",
    group: "organs",
    impact: "support",
    impactSummary: "Novo envelope requer revisão de cobertura e rota de fuga.",
    workItem: "Validar cobertura, acesso e classificação do equipamento.",
    owner: "Líder de Incêndio",
  },
];

export const roles: RolePersona[] = [
  {
    id: "project-manager",
    name: "Gerente do Projeto",
    focus: "Fechar a mudança sem perder o marco executivo.",
    assignment: "Aprovar donos, prazos e critérios de fechamento do plano integrado.",
    evidence: ["Revisão C aprovada", "Matriz de impacto", "Caminho crítico"],
    deliverable: "Decisão coordenada de liberação",
  },
  {
    id: "electrical",
    name: "Líder de Elétrica",
    focus: "Absorver o aumento de 15% da carga instalada.",
    assignment: "Atualizar lista de cargas, alimentador e unifilar; devolver para revisão BIM.",
    evidence: ["Data sheet Rev. C §4.2", "Lista de cargas Rev. 7", "Premissa EL-014"],
    deliverable: "Pacote elétrico Rev. 8 — rascunho",
  },
  {
    id: "bim",
    name: "Coordenador BIM",
    focus: "Reconciliar o footprint revisado com o modelo federado.",
    assignment: "Gerar scaffold, reposicionar conexões e validar zonas de interferência.",
    evidence: ["Layout Rev. 4", "Data sheet Rev. C", "BEP §6.1"],
    deliverable: "Scaffold BIM conceitual — rascunho",
  },
  {
    id: "planning",
    name: "Engenheiro de Planejamento",
    focus: "Recuperar o atraso de 10 dias sem mascarar dependências.",
    assignment: "Simular recuperação, sequenciamento e nova folga do gate executivo.",
    evidence: ["Cronograma base Rev. 12", "Log do fornecedor", "Dependências de revisão"],
    deliverable: "Opções de recuperação — para decisão",
  },
  {
    id: "quality",
    name: "Líder de Qualidade",
    focus: "Garantir que nenhuma disciplina libere premissas antigas.",
    assignment: "Verificar seis aprovações e evidências antes de desbloquear o gate.",
    evidence: ["Checklist Gate EXE-02", "Registro de aprovações", "Mapa de supersessão"],
    deliverable: "Parecer de prontidão do gate",
  },
];

export const workflowSteps: WorkflowStep[] = [
  {
    id: "source",
    title: "Evento recebido do Slack",
    detail: "Mensagem e anexo preservados como evidência; ainda não são verdade oficial.",
    kind: "deterministic",
    availableAt: 1,
  },
  {
    id: "compare",
    title: "Revisões B e C comparadas",
    detail: "Quatro diferenças materiais extraídas com referência à fonte.",
    kind: "agentic",
    availableAt: 2,
  },
  {
    id: "approval",
    title: "Mudança aprovada",
    detail: "Gerente do Projeto confirmou a Rev. C como premissa vigente.",
    kind: "human",
    availableAt: 3,
  },
  {
    id: "dependencies",
    title: "Dependências mapeadas",
    detail: "Quinze disciplinas avaliadas; dez exigem ação ou verificação.",
    kind: "agentic",
    availableAt: 4,
  },
  {
    id: "packets",
    title: "Pacotes de trabalho montados",
    detail: "Insumos, fontes, critérios, donos e entregáveis agrupados por disciplina.",
    kind: "deterministic",
    availableAt: 5,
  },
  {
    id: "tools",
    title: "Ferramentas de execução iniciadas",
    detail: "Cálculos, scaffold BIM, cenário de prazo e validações executados em sandbox.",
    kind: "agentic",
    availableAt: 6,
  },
  {
    id: "reviews",
    title: "Revisões humanas registradas",
    detail: "Responsáveis técnicos aceitaram, corrigiram ou bloquearam os rascunhos.",
    kind: "human",
    availableAt: 7,
  },
  {
    id: "release",
    title: "Gate liberado",
    detail: "Evidências completas, dependências fechadas e pacote pronto para emissão.",
    kind: "deterministic",
    availableAt: 8,
  },
];

export const artifacts: Artifact[] = [
  {
    id: "revision-comparison",
    title: "Comparativo Rev. B × Rev. C",
    type: "Análise documental",
    description: "Footprint, carga, água gelada e prazo com trechos de origem vinculados.",
    owner: "Urso · Document Intelligence",
    availableAt: 2,
    validation: "4 diferenças verificadas",
    discipline: "Coordenação do Projeto",
    sources: ["Data Sheet Rev. B", "Data Sheet Rev. C", "Registro do fornecedor SUP-118"],
    findings: ["Envelope +1,2 m", "Carga elétrica +15%", "Água gelada +18%", "Entrega +10 dias"],
    actions: ["Confirmar mudança material", "Preservar Rev. B como superseded", "Propagar premissas aprovadas"],
  },
  {
    id: "impact-plan",
    title: "Plano de impacto integrado",
    type: "Coordenação",
    description: "Ações, dependências, responsáveis e critérios de fechamento para 15 disciplinas.",
    owner: "Gerente do Projeto",
    availableAt: 5,
    validation: "15 disciplinas avaliadas",
    discipline: "Gerenciamento do Projeto",
    sources: ["DEC-042", "Matriz de dependências", "Plano executivo EXE-02"],
    findings: ["5 ações críticas", "3 revisões técnicas", "2 verificações", "5 disciplinas estáveis"],
    actions: ["Designar responsáveis", "Definir critérios de fechamento", "Monitorar bloqueios do gate"],
  },
  {
    id: "electrical-package",
    title: "Pacote elétrico Rev. 8",
    type: "Pacote disciplinar",
    description: "Lista de cargas, alimentador e unifilar preparados para o aumento de potência da linha.",
    owner: "Líder de Elétrica",
    availableAt: 6,
    validation: "Carga e alimentador recalculados",
    discipline: "Elétrica",
    sources: ["Data Sheet Rev. C §4.2", "Lista de Cargas Rev. 7", "Premissa EL-014"],
    findings: ["Carga da linha: 640 → 736 kW", "Demanda do painel: 812 → 908 kVA", "Reserva atual abaixo do limite MF"],
    actions: ["Confirmar alimentador 4×240 mm²", "Atualizar diagrama unifilar", "Devolver ocupação para coordenação BIM"],
  },
  {
    id: "hvac-package",
    title: "Pacote HVAC Rev. 6",
    type: "Pacote disciplinar",
    description: "Balanço térmico, vazão e conexão revisados para o aumento de água gelada.",
    owner: "Líder de HVAC",
    availableAt: 6,
    validation: "Balanço e vazão reconciliados",
    discipline: "HVAC",
    sources: ["Data Sheet Rev. C §5.4", "Memória HVAC Rev. 5", "Diagrama CHW-03"],
    findings: ["Demanda: 420 → 496 kW", "Vazão: 20,1 → 23,7 l/s", "Chiller mantém 8% de reserva"],
    actions: ["Atualizar memória de cálculo", "Revisar válvula de controle", "Coordenar nova conexão com Mecânica"],
  },
  {
    id: "bim-scaffold",
    title: "Scaffold BIM conceitual",
    type: "Modelo de apoio",
    description: "Envelope antes/depois, conexões, clearances e zonas de roteamento afetadas.",
    owner: "Coordenação BIM",
    availableAt: 6,
    validation: "2 interferências para revisão",
    discipline: "Metodologia BIM",
    sources: ["Layout Rev. 4", "Data Sheet Rev. C", "BEP §6.1"],
    findings: ["Envelope deslocado 1,2 m", "Clearance sul reduzido", "Duas interferências de utilidades"],
    actions: ["Reposicionar conexões", "Revisar faixa de manutenção", "Emitir modelo federado para coordenação"],
  },
  {
    id: "recovery-plan",
    title: "Opções de recuperação do marco",
    type: "Planejamento",
    description: "Três cenários comparados por prazo, risco técnico e dependências críticas.",
    owner: "Planejamento e Controle",
    availableAt: 6,
    validation: "Opção B recupera 7 dias",
    discipline: "Planejamento e Controle",
    sources: ["Cronograma Base Rev. 12", "Log do fornecedor", "Matriz de dependências"],
    findings: ["Cenário A mantém atraso de 10 dias", "Cenário B recupera 7 dias", "Cenário C recupera 10 dias com alto risco"],
    actions: ["Selecionar cenário B", "Antecipar revisão interdisciplinar", "Proteger folga do gate EXE-02"],
  },
  {
    id: "gate-checklist",
    title: "Checklist de prontidão EXE-02",
    type: "Qualidade",
    description: "Evidências e aprovações requeridas antes da liberação executiva.",
    owner: "Qualidade",
    availableAt: 7,
    validation: "6 de 6 revisões concluídas",
    discipline: "Qualidade",
    sources: ["Checklist EXE-02", "Registro de aprovações", "Receipts do workflow"],
    findings: ["6 aprovações técnicas presentes", "2 clashes BIM fechados", "Rev. B removida dos pacotes ativos"],
    actions: ["Verificar hashes finais", "Confirmar plano de recuperação", "Liberar emissão executiva"],
  },
  {
    id: "teams-update",
    title: "Atualização coordenada para o Teams",
    type: "Comunicação operacional",
    description: "Resumo de decisão, ações por disciplina, prazos e links para os novos pacotes.",
    owner: "Urso Harness · aprovação do PM",
    availableAt: 7,
    validation: "Destinatários e links verificados",
    discipline: "Gerenciamento do Projeto",
    sources: ["DEC-042", "Plano de impacto integrado", "Status dos pacotes"],
    findings: ["10 disciplinas notificadas", "5 responsáveis críticos marcados", "Gate EXE-02 atualizado"],
    actions: ["Revisar texto", "Confirmar audiência", "Publicar no canal do projeto"],
  },
];

export const activityEvents: ActivityEvent[] = [
  {
    id: "baseline",
    time: "08:20",
    title: "Baseline sincronizada",
    detail: "Gate executivo em 14 dias; risco baixo.",
    availableAt: 0,
    tone: "neutral",
  },
  {
    id: "revision-c",
    time: "09:42",
    title: "Revisão C detectada",
    detail: "Slack · #fornecedor-linha",
    availableAt: 1,
    tone: "cyan",
  },
  {
    id: "candidate-change",
    time: "09:43",
    title: "Mudança material proposta",
    detail: "4 diferenças requerem aprovação.",
    availableAt: 2,
    tone: "warning",
  },
  {
    id: "approved",
    time: "09:47",
    title: "Rev. C aprovada",
    detail: "Rev. B preservada como superseded.",
    availableAt: 3,
    tone: "positive",
  },
  {
    id: "mapped",
    time: "09:48",
    title: "Impacto propagado",
    detail: "10 disciplinas exigem ação ou revisão.",
    availableAt: 4,
    tone: "cyan",
  },
  {
    id: "packets",
    time: "09:49",
    title: "Pacotes distribuídos",
    detail: "Donos e critérios enviados ao projeto.",
    availableAt: 5,
    tone: "cyan",
  },
  {
    id: "execution",
    time: "09:54",
    title: "Ferramentas concluídas",
    detail: "8 artefatos aguardam revisão humana.",
    availableAt: 6,
    tone: "warning",
  },
  {
    id: "reviewed",
    time: "10:18",
    title: "Revisões técnicas concluídas",
    detail: "Gate pronto para verificação final.",
    availableAt: 7,
    tone: "positive",
  },
  {
    id: "released",
    time: "10:21",
    title: "Marco pronto para liberação",
    detail: "Trilha de evidência completa.",
    availableAt: 8,
    tone: "positive",
  },
];

export const askUrsoAnswers = [
  {
    question: "Por que o risco do projeto mudou?",
    answer:
      "A Revisão C alterou quatro premissas. O atraso de 10 dias cruza o caminho crítico; o aumento de 15% da carga e 18% da água gelada bloqueia a liberação até Elétrica, HVAC, BIM e Qualidade concluírem suas revisões.",
    sources: "Data Sheet Rev. C §§2.1, 4.2 e 5.4 · Cronograma Rev. 12",
  },
  {
    question: "O que está bloqueando Elétrica?",
    answer:
      "A lista de cargas ainda usa a potência da Revisão B. Elétrica precisa validar o alimentador revisado e devolver o unifilar para coordenação BIM antes do gate EXE-02.",
    sources: "Pacote ELE-08 · Premissa EL-014 · Checklist EXE-02",
  },
  {
    question: "Qual documento está aprovado agora?",
    answer:
      "Filling Line Data Sheet — Revisão C é a versão vigente desde 09:47. A Revisão B foi preservada no histórico como superseded e não deve orientar novos entregáveis.",
    sources: "Registro de decisão DEC-042 · Histórico de versões",
  },
  {
    question: "O que falta para liberar o projeto executivo?",
    answer:
      "Faltam as revisões técnicas dos quatro artefatos gerados, o fechamento das duas interferências BIM e a confirmação do plano de recuperação pelo Gerente do Projeto.",
    sources: "Gate EXE-02 · Workflow WF-REV-C-001",
  },
] as const;
