const text = (pt, en) => ({ pt, en });

function deepFreeze(value) {
  if (value && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
  }
  return value;
}

export const mfScenarioManifest = deepFreeze({
  id: "supplier-revision-c",
  project: {
    id: "uberlandia-refrescos-f3",
    name: "Uberlândia Refrescos",
    phase: text("Fase 3", "Phase 3"),
    stage: text("Projeto executivo", "Executive design"),
    location: "Uberlândia, MG",
    milestone: "EXE-02",
    milestoneName: text("Liberação do projeto executivo", "Executive design release"),
    targetDate: "2026-08-18",
    publicFacts: text(
      "49.350 m² · 80.000 garrafas/hora · expansão industrial",
      "49,350 m² · 80,000 bottles/hour · industrial expansion",
    ),
  },
  revisions: {
    B: {
      footprintM: [18.4, 4.8],
      electricalKw: 420,
      chilledWaterKw: 118,
      operatingLoadKn: 146,
    },
    C: {
      footprintM: [19.6, 5.1],
      electricalKw: 483,
      chilledWaterKw: 139,
      operatingLoadKn: 168,
    },
  },
  decision: {
    id: "DEC-042",
    title: text("Aprovar a Revisão C como verdade atual", "Approve Revision C as current truth"),
    approvingRoleId: "project-manager",
    effectiveDate: "2026-08-01",
  },
  objective: {
    id: "OBJ-EXE-02",
    title: text(
      "Proteger a liberação EXE-02 até 18 de agosto",
      "Protect the EXE-02 release by August 18",
    ),
    detail: text(
      "Resolver todas as dependências da Revisão C com evidência, responsáveis e controle humano.",
      "Resolve every Revision C dependency with evidence, owners, and human control.",
    ),
  },
  outcome: {
    exposureDays: 10,
    recoveredDays: 8,
    sequentialDate: "2026-08-26",
    coordinatedDate: "2026-08-18",
  },
  sources: [
    {
      id: "supplier-communication",
      name: text("Comunicação do fornecedor", "Supplier communication"),
      system: "Slack",
      type: text("Evento + anexo", "Event + attachment"),
      mode: "demo",
      authority: "evidence",
      freshness: text("Recebido agora", "Received now"),
      owner: text("Suprimentos do projeto", "Project procurement"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/03 Supplier Sources/Slack Event — Supplier Revision C.md"],
    },
    {
      id: "controlled-documents",
      name: text("Documentos controlados", "Controlled documents"),
      system: "CDE",
      type: text("Data sheets e layouts", "Data sheets and layouts"),
      mode: "live",
      authority: "controlled",
      freshness: text("Sincronizado há 2 min", "Synced 2 min ago"),
      owner: text("Controle de documentos", "Document control"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/03 Supplier Sources/Filling Line Data Sheet — Revision B.md", "MF Demo Brain Corpus/03 Supplier Sources/Filling Line Data Sheet — Revision C.md"],
    },
    {
      id: "bim-models",
      name: text("Modelos BIM", "BIM models"),
      system: "CDE / Revit",
      type: text("Modelo federado", "Federated model"),
      mode: "demo",
      authority: "working",
      freshness: text("Federação Rev. 17", "Federation Rev. 17"),
      owner: text("Coordenação BIM", "BIM coordination"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/02 Project Baseline/BIM Execution Plan.md", "MF Demo Brain Corpus/06 BIM and Coordination/Concept BIM Scaffold — Revision C.md"],
    },
    {
      id: "project-schedule",
      name: text("Cronograma do projeto", "Project schedule"),
      system: "Primavera P6",
      type: text("Baseline e caminho crítico", "Baseline and critical path"),
      mode: "demo",
      authority: "controlled",
      freshness: text("Baseline Rev. 12", "Baseline Rev. 12"),
      owner: text("Planejamento e Controle", "Planning and Control"),
      authorizedRoleIds: ["project-manager", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/02 Project Baseline/Baseline Schedule — Rev 12.md", "MF Demo Brain Corpus/04 Decisions and Changes/Recovery Plan — Revision C.md"],
    },
    {
      id: "engineering-standards",
      name: text("Normas e premissas", "Standards and assumptions"),
      system: "Urso Brain",
      type: text("Regras controladas", "Controlled rules"),
      mode: "live",
      authority: "policy",
      freshness: text("Versão atual", "Current version"),
      owner: text("Engenharia e Qualidade", "Engineering and Quality"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/02 Project Baseline/Approved Project Premises.md", "MF Demo Brain Corpus/00 Company Core/Material Change Approval Rule.md"],
    },
    {
      id: "rfi-decisions",
      name: text("RFIs e decisões", "RFIs and decisions"),
      system: "CDE",
      type: text("Registro decisório", "Decision register"),
      mode: "live",
      authority: "decision",
      freshness: text("DEC-042 pendente", "DEC-042 pending"),
      owner: text("Gerência do Projeto", "Project Management"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/04 Decisions and Changes/Revision C Approval — DEC-042.md", "MF Demo Brain Corpus/03 Supplier Sources/Open RFI — Utility Coordinates.md"],
    },
    {
      id: "team-coordination",
      name: text("Coordenação da equipe", "Team coordination"),
      system: "Teams",
      type: text("Ações e handoffs", "Actions and handoffs"),
      mode: "pilot",
      authority: "coordination",
      freshness: text("Conexão no piloto", "Pilot connection"),
      owner: text("Gerência do Projeto", "Project Management"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/01 Project Governance/Project Communication Protocol.md"],
    },
    {
      id: "identity-permissions",
      name: text("Identidade e permissões", "Identity and permissions"),
      system: "Urso Brain",
      type: text("Papéis e acesso", "Roles and access"),
      mode: "live",
      authority: "security",
      freshness: text("Avaliado por solicitação", "Evaluated per request"),
      owner: text("Governança do projeto", "Project governance"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/01 Project Governance/Project RACI and Approval Matrix.md", "MF Demo Brain Corpus/00 Company Core/Evidence and Source Authority Rule.md"],
    },
  ],
  roles: [
    {
      id: "project-manager",
      departmentId: "planning",
      name: text("Gerente do Projeto", "Project Manager"),
      objective: text("Fechar a mudança sem perder o marco executivo.", "Close the change without losing the executive milestone."),
      assignment: text("Aprovar a verdade, os responsáveis e o plano integrado.", "Approve the truth, owners, and integrated plan."),
      deliverable: text("Decisão coordenada de liberação", "Coordinated release decision"),
    },
    {
      id: "electrical",
      departmentId: "electrical",
      name: text("Líder de Elétrica", "Electrical Lead"),
      objective: text("Absorver o aumento de 15% da carga instalada.", "Absorb the 15% increase in installed load."),
      assignment: text("Atualizar lista de cargas, alimentador e unifilar.", "Update the load list, feeder, and single-line diagram."),
      deliverable: text("Pacote elétrico Rev. 8", "Electrical package Rev. 8"),
    },
    {
      id: "bim",
      departmentId: "bim",
      name: text("Coordenador BIM", "BIM Coordinator"),
      objective: text("Reconciliar o footprint com o modelo federado.", "Reconcile the footprint with the federated model."),
      assignment: text("Reposicionar conexões e validar interferências.", "Reposition connections and validate clashes."),
      deliverable: text("Scaffold BIM conceitual", "Concept BIM scaffold"),
    },
    {
      id: "planning",
      departmentId: "planning",
      name: text("Engenheiro de Planejamento", "Planning Engineer"),
      objective: text("Recuperar oito dias sem mascarar dependências.", "Recover eight days without hiding dependencies."),
      assignment: text("Simular sequenciamento e recalcular o caminho crítico.", "Simulate sequencing and recalculate the critical path."),
      deliverable: text("Plano de recuperação do marco", "Milestone recovery plan"),
    },
    {
      id: "quality",
      departmentId: "quality",
      name: text("Líder de Qualidade", "Quality Lead"),
      objective: text("Impedir a liberação de premissas antigas.", "Prevent release using superseded assumptions."),
      assignment: text("Verificar evidências e aprovações antes do gate.", "Verify evidence and approvals before the gate."),
      deliverable: text("Parecer de prontidão EXE-02", "EXE-02 readiness opinion"),
    },
  ],
  disciplines: [
    ["viability", "Viabilidade", "Viability", false, "none"],
    ["bid", "BID", "BID", false, "none"],
    ["planning", "Planejamento e Controle", "Planning and Control", true, "critical"],
    ["quality", "Qualidade", "Quality", true, "watch"],
    ["bim", "Metodologia BIM", "BIM Methodology", true, "critical"],
    ["architecture", "Arquitetura", "Architecture", true, "support"],
    ["infrastructure", "Infraestrutura", "Infrastructure", false, "none"],
    ["concrete", "Estruturas de Concreto", "Concrete Structures", true, "critical"],
    ["steel", "Estruturas Metálicas", "Steel Structures", false, "none"],
    ["hydraulics", "Hidráulica", "Hydraulics", false, "none"],
    ["hvac", "HVAC", "HVAC", true, "critical"],
    ["electrical", "Elétrica", "Electrical", true, "critical"],
    ["mechanical", "Mecânica e Tubulação", "Mechanical and Piping", true, "watch"],
    ["automation", "Sistemas Especiais e Automação", "Special Systems and Automation", true, "watch"],
    ["fire", "Proteção Contra Incêndio", "Fire Protection", true, "support"],
  ].map(([id, pt, en, impacted, impact]) => ({ id, name: text(pt, en), impacted, impact })),
  workflow: {
    id: "change-propagation@2.0",
    tasks: [
      {
        id: "approve-controlled-truth",
        ownerRoleId: "project-manager",
        title: text("Aprovar a verdade controlada", "Approve controlled truth"),
        detail: text("Confirmar materialidade e efetivar DEC-042.", "Confirm materiality and enact DEC-042."),
        dependsOn: [],
        sourceIds: ["supplier-communication", "controlled-documents", "rfi-decisions"],
        artifactId: "revision-comparison",
        humanGate: true,
      },
      {
        id: "map-impact",
        ownerRoleId: "project-manager",
        title: text("Ativar o plano de impacto", "Activate the impact plan"),
        detail: text("Confirmar disciplinas, responsáveis e critérios de fechamento.", "Confirm disciplines, owners, and closure criteria."),
        dependsOn: ["approve-controlled-truth"],
        sourceIds: ["controlled-documents", "identity-permissions"],
        artifactId: "impact-plan",
        humanGate: false,
      },
      {
        id: "coordinate-bim",
        ownerRoleId: "bim",
        title: text("Coordenar o novo envelope", "Coordinate the new envelope"),
        detail: text("Reposicionar conexões e identificar interferências.", "Reposition connections and identify clashes."),
        dependsOn: ["map-impact"],
        sourceIds: ["controlled-documents", "bim-models"],
        artifactId: "bim-scaffold",
        humanGate: true,
      },
      {
        id: "update-electrical",
        ownerRoleId: "electrical",
        title: text("Atualizar o pacote elétrico", "Update the electrical package"),
        detail: text("Recalcular 420 → 483 kW e devolver a ocupação ao BIM.", "Recalculate 420 → 483 kW and return routing space to BIM."),
        dependsOn: ["coordinate-bim"],
        sourceIds: ["controlled-documents", "engineering-standards", "bim-models"],
        artifactId: "electrical-package",
        humanGate: true,
      },
      {
        id: "recover-schedule",
        ownerRoleId: "planning",
        title: text("Recuperar o cronograma", "Recover the schedule"),
        detail: text("Sobrepor revisões controladas e recuperar oito dias.", "Overlap controlled reviews and recover eight days."),
        dependsOn: ["map-impact"],
        sourceIds: ["project-schedule", "rfi-decisions"],
        artifactId: "recovery-plan",
        humanGate: true,
      },
      {
        id: "verify-gate",
        ownerRoleId: "quality",
        title: text("Verificar prontidão do gate", "Verify gate readiness"),
        detail: text("Confirmar evidências, aprovações e remoção da Rev. B.", "Confirm evidence, approvals, and removal of Rev. B."),
        dependsOn: ["update-electrical", "recover-schedule"],
        sourceIds: ["engineering-standards", "rfi-decisions", "identity-permissions"],
        artifactId: "gate-checklist",
        humanGate: true,
      },
      {
        id: "release-exe-02",
        ownerRoleId: "project-manager",
        title: text("Liberar EXE-02", "Release EXE-02"),
        detail: text("Confirmar prontidão e publicar a decisão coordenada.", "Confirm readiness and publish the coordinated decision."),
        dependsOn: ["verify-gate"],
        sourceIds: ["rfi-decisions", "team-coordination"],
        artifactId: "teams-update",
        humanGate: true,
      },
    ],
  },
  story: [
    { step: 0, state: "baseline", stage: text("Projeto sob controle", "Project under control") },
    { step: 1, state: "event_detected", stage: text("Mudança detectada", "Change detected") },
    { step: 2, state: "awaiting_change_approval", stage: text("Verdade em análise", "Truth under review") },
    { step: 3, state: "change_approved", stage: text("Verdade controlada", "Truth controlled") },
    { step: 4, state: "impact_mapping", stage: text("Impacto compreendido", "Impact understood") },
    { step: 5, state: "work_packets_ready", stage: text("Trabalho coordenado", "Work coordinated") },
    { step: 6, state: "execution_in_progress", stage: text("Objetivos em execução", "Objectives in progress") },
    { step: 7, state: "reviews_pending", stage: text("Evidências verificadas", "Evidence verified") },
    { step: 8, state: "release_ready", stage: text("Liberação protegida", "Release protected") },
  ],
});

export function mfText(value, language = "pt") {
  return value[language === "en" ? "en" : "pt"];
}
