const text = (pt, en) => ({ pt, en });

function deepFreeze(value) {
  if (value && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
  }
  return value;
}

export const mfScenarioManifest = deepFreeze({
  id: "supplier-revision-c",
  project: {
    id: "uberlandia-refrescos-f3",
    name: "Uberlândia Refrescos",
    phase: text("Fase 3", "Phase 3"),
    stage: text("Projeto executivo", "Executive design"),
    location: "Uberlândia, MG",
    milestone: "EXE-02",
    milestoneName: text("Liberação do projeto executivo", "Executive design release"),
    targetDate: "2026-08-18",
    publicFacts: text(
      "49.350 m² · 80.000 garrafas/hora · expansão industrial",
      "49,350 m² · 80,000 bottles/hour · industrial expansion",
    ),
  },
  revisions: {
    B: {
      footprintM: [18.4, 4.8],
      electricalKw: 420,
      chilledWaterKw: 118,
      operatingLoadKn: 146,
    },
    C: {
      footprintM: [19.6, 5.1],
      electricalKw: 483,
      chilledWaterKw: 139,
      operatingLoadKn: 168,
    },
  },
  decision: {
    id: "DEC-042",
    title: text("Aprovar a Revisão C como verdade atual", "Approve Revision C as current truth"),
    approvingRoleId: "project-manager",
    effectiveDate: "2026-08-01",
  },
  objective: {
    id: "OBJ-EXE-02",
    title: text(
      "Proteger a liberação EXE-02 até 18 de agosto",
      "Protect the EXE-02 release by August 18",
    ),
    detail: text(
      "Resolver todas as dependências da Revisão C com evidência, responsáveis e controle humano.",
      "Resolve every Revision C dependency with evidence, owners, and human control.",
    ),
  },
  outcome: {
    exposureDays: 10,
    recoveredDays: 8,
    sequentialDate: "2026-08-26",
    coordinatedDate: "2026-08-18",
  },
  sources: [
    {
      id: "supplier-communication",
      name: text("Comunicação do fornecedor", "Supplier communication"),
      system: "Slack",
      technology: { id: "slack", name: "Slack" },
      type: text("Evento + anexo", "Event + attachment"),
      mode: "demo",
      authority: "evidence",
      freshness: text("Recebido agora", "Received now"),
      owner: text("Suprimentos do projeto", "Project procurement"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/03 Supplier Sources/Slack Event — Supplier Revision C.md"],
    },
    {
      id: "controlled-documents",
      name: text("Documentos controlados", "Controlled documents"),
      system: "CDE",
      technology: { id: "cde", name: "CDE" },
      type: text("Data sheets e layouts", "Data sheets and layouts"),
      mode: "live",
      authority: "controlled",
      freshness: text("Sincronizado há 2 min", "Synced 2 min ago"),
      owner: text("Controle de documentos", "Document control"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/03 Supplier Sources/Filling Line Data Sheet — Revision B.md", "MF Demo Brain Corpus/03 Supplier Sources/Filling Line Data Sheet — Revision C.md"],
    },
    {
      id: "bim-models",
      name: text("Modelos BIM", "BIM models"),
      system: "CDE / Revit",
      technology: { id: "revit", name: "Revit" },
      type: text("Modelo federado", "Federated model"),
      mode: "demo",
      authority: "working",
      freshness: text("Federação Rev. 17", "Federation Rev. 17"),
      owner: text("Coordenação BIM", "BIM coordination"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/02 Project Baseline/BIM Execution Plan.md", "MF Demo Brain Corpus/06 BIM and Coordination/Concept BIM Scaffold — Revision C.md"],
    },
    {
      id: "project-schedule",
      name: text("Cronograma do projeto", "Project schedule"),
      system: "Primavera P6",
      technology: { id: "primavera-p6", name: "Primavera P6" },
      type: text("Baseline e caminho crítico", "Baseline and critical path"),
      mode: "demo",
      authority: "controlled",
      freshness: text("Baseline Rev. 12", "Baseline Rev. 12"),
      owner: text("Planejamento e Controle", "Planning and Control"),
      authorizedRoleIds: ["project-manager", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/02 Project Baseline/Baseline Schedule — Rev 12.md", "MF Demo Brain Corpus/04 Decisions and Changes/Recovery Plan — Revision C.md"],
    },
    {
      id: "engineering-standards",
      name: text("Normas e premissas", "Standards and assumptions"),
      system: "Urso Brain",
      technology: { id: "urso-brain", name: "Urso Brain" },
      type: text("Regras controladas", "Controlled rules"),
      mode: "live",
      authority: "policy",
      freshness: text("Versão atual", "Current version"),
      owner: text("Engenharia e Qualidade", "Engineering and Quality"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/02 Project Baseline/Approved Project Premises.md", "MF Demo Brain Corpus/00 Company Core/Material Change Approval Rule.md"],
    },
    {
      id: "rfi-decisions",
      name: text("RFIs e decisões", "RFIs and decisions"),
      system: "CDE",
      technology: { id: "cde", name: "CDE" },
      type: text("Registro decisório", "Decision register"),
      mode: "live",
      authority: "decision",
      freshness: text("DEC-042 pendente", "DEC-042 pending"),
      owner: text("Gerência do Projeto", "Project Management"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/04 Decisions and Changes/Revision C Approval — DEC-042.md", "MF Demo Brain Corpus/03 Supplier Sources/Open RFI — Utility Coordinates.md"],
    },
    {
      id: "team-coordination",
      name: text("Coordenação da equipe", "Team coordination"),
      system: "Teams",
      technology: { id: "teams", name: "Teams" },
      type: text("Ações e handoffs", "Actions and handoffs"),
      mode: "pilot",
      authority: "coordination",
      freshness: text("Conexão no piloto", "Pilot connection"),
      owner: text("Gerência do Projeto", "Project Management"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/01 Project Governance/Project Communication Protocol.md"],
    },
    {
      id: "identity-permissions",
      name: text("Identidade e permissões", "Identity and permissions"),
      system: "Urso Brain",
      technology: { id: "urso-brain", name: "Urso Brain" },
      type: text("Papéis e acesso", "Roles and access"),
      mode: "live",
      authority: "security",
      freshness: text("Avaliado por solicitação", "Evaluated per request"),
      owner: text("Governança do projeto", "Project governance"),
      authorizedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      evidencePaths: ["MF Demo Brain Corpus/01 Project Governance/Project RACI and Approval Matrix.md", "MF Demo Brain Corpus/00 Company Core/Evidence and Source Authority Rule.md"],
    },
  ],
  roles: [
    {
      id: "project-manager",
      departmentId: "planning",
      name: text("Gerente do Projeto", "Project Manager"),
      objective: text("Fechar a mudança sem perder o marco executivo.", "Close the change without losing the executive milestone."),
      assignment: text("Aprovar a verdade, os responsáveis e o plano integrado.", "Approve the truth, owners, and integrated plan."),
      deliverable: text("Decisão coordenada de liberação", "Coordinated release decision"),
    },
    {
      id: "electrical",
      departmentId: "electrical",
      name: text("Líder de Elétrica", "Electrical Lead"),
      objective: text("Absorver o aumento de 15% da carga instalada.", "Absorb the 15% increase in installed load."),
      assignment: text("Atualizar lista de cargas, alimentador e unifilar.", "Update the load list, feeder, and single-line diagram."),
      deliverable: text("Pacote elétrico Rev. 8", "Electrical package Rev. 8"),
    },
    {
      id: "bim",
      departmentId: "bim",
      name: text("Coordenador BIM", "BIM Coordinator"),
      objective: text("Reconciliar o footprint com o modelo federado.", "Reconcile the footprint with the federated model."),
      assignment: text("Reposicionar conexões e validar interferências.", "Reposition connections and validate clashes."),
      deliverable: text("Scaffold BIM conceitual", "Concept BIM scaffold"),
    },
    {
      id: "planning",
      departmentId: "planning",
      name: text("Engenheiro de Planejamento", "Planning Engineer"),
      objective: text("Recuperar oito dias sem mascarar dependências.", "Recover eight days without hiding dependencies."),
      assignment: text("Simular sequenciamento e recalcular o caminho crítico.", "Simulate sequencing and recalculate the critical path."),
      deliverable: text("Plano de recuperação do marco", "Milestone recovery plan"),
    },
    {
      id: "quality",
      departmentId: "quality",
      name: text("Líder de Qualidade", "Quality Lead"),
      objective: text("Impedir a liberação de premissas antigas.", "Prevent release using superseded assumptions."),
      assignment: text("Verificar evidências e aprovações antes do gate.", "Verify evidence and approvals before the gate."),
      deliverable: text("Parecer de prontidão EXE-02", "EXE-02 readiness opinion"),
    },
  ],
  disciplines: [
    ["viability", "Viabilidade", "Viability", false, "none"],
    ["bid", "BID", "BID", false, "none"],
    ["planning", "Planejamento e Controle", "Planning and Control", true, "critical"],
    ["quality", "Qualidade", "Quality", true, "watch"],
    ["bim", "Metodologia BIM", "BIM Methodology", true, "critical"],
    ["architecture", "Arquitetura", "Architecture", true, "support"],
    ["infrastructure", "Infraestrutura", "Infrastructure", false, "none"],
    ["concrete", "Estruturas de Concreto", "Concrete Structures", true, "critical"],
    ["steel", "Estruturas Metálicas", "Steel Structures", false, "none"],
    ["hydraulics", "Hidráulica", "Hydraulics", false, "none"],
    ["hvac", "HVAC", "HVAC", true, "critical"],
    ["electrical", "Elétrica", "Electrical", true, "critical"],
    ["mechanical", "Mecânica e Tubulação", "Mechanical and Piping", true, "watch"],
    ["automation", "Sistemas Especiais e Automação", "Special Systems and Automation", true, "watch"],
    ["fire", "Proteção Contra Incêndio", "Fire Protection", true, "support"],
  ].map(([id, pt, en, impacted, impact]) => ({ id, name: text(pt, en), impacted, impact })),
  workflow: {
    id: "change-propagation@2.0",
    tasks: [
      {
        id: "approve-controlled-truth",
        ownerRoleId: "project-manager",
        title: text("Aprovar a verdade controlada", "Approve controlled truth"),
        detail: text("Confirmar materialidade e efetivar DEC-042.", "Confirm materiality and enact DEC-042."),
        dependsOn: [],
        sourceIds: ["supplier-communication", "controlled-documents", "rfi-decisions"],
        artifactId: "revision-comparison",
        humanGate: true,
        managerAction: {
          id: "DEC-042",
          kind: "decision",
          label: text("Aprovar verdade controlada", "Approve controlled truth"),
          due: text("Hoje · 12:00", "Today · 12:00"),
          actionAt: 2,
          blockedLane: "next",
        },
      },
      {
        id: "map-impact",
        ownerRoleId: "project-manager",
        title: text("Ativar o plano de impacto", "Activate the impact plan"),
        detail: text("Confirmar disciplinas, responsáveis e critérios de fechamento.", "Confirm disciplines, owners, and closure criteria."),
        dependsOn: ["approve-controlled-truth"],
        sourceIds: ["controlled-documents", "identity-permissions"],
        artifactId: "impact-plan",
        humanGate: false,
        managerAction: {
          id: "ACT-IMPACT",
          kind: "action",
          label: text("Ativar o plano de impacto", "Activate the impact plan"),
          due: text("Hoje · 14:00", "Today · 14:00"),
          actionAt: 3,
          blockedLane: "next",
        },
      },
      {
        id: "coordinate-bim",
        ownerRoleId: "bim",
        title: text("Coordenar o novo envelope", "Coordinate the new envelope"),
        detail: text("Reposicionar conexões e identificar interferências.", "Reposition connections and identify clashes."),
        dependsOn: ["map-impact"],
        sourceIds: ["controlled-documents", "bim-models"],
        artifactId: "bim-scaffold",
        humanGate: true,
      },
      {
        id: "update-electrical",
        ownerRoleId: "electrical",
        title: text("Atualizar o pacote elétrico", "Update the electrical package"),
        detail: text("Recalcular 420 → 483 kW e devolver a ocupação ao BIM.", "Recalculate 420 → 483 kW and return routing space to BIM."),
        dependsOn: ["coordinate-bim"],
        sourceIds: ["controlled-documents", "engineering-standards", "bim-models"],
        artifactId: "electrical-package",
        humanGate: true,
      },
      {
        id: "recover-schedule",
        ownerRoleId: "planning",
        title: text("Recuperar o cronograma", "Recover the schedule"),
        detail: text("Sobrepor revisões controladas e recuperar oito dias.", "Overlap controlled reviews and recover eight days."),
        dependsOn: ["map-impact"],
        sourceIds: ["project-schedule", "rfi-decisions"],
        artifactId: "recovery-plan",
        humanGate: true,
      },
      {
        id: "select-recovery-scenario",
        ownerRoleId: "project-manager",
        title: text("Selecionar cenário de recuperação", "Select recovery scenario"),
        detail: text(
          "Escolher a revisão paralela controlada preparada por Planejamento.",
          "Choose the controlled parallel-review scenario prepared by Planning.",
        ),
        dependsOn: ["recover-schedule"],
        sourceIds: ["project-schedule", "rfi-decisions"],
        artifactId: "recovery-plan",
        humanGate: true,
        managerAction: {
          id: "SCN-003",
          kind: "decision",
          label: text("Selecionar cenário de recuperação", "Select recovery scenario"),
          due: text("Hoje · 16:00", "Today · 16:00"),
          actionAt: 6,
          blockedLane: "next",
        },
      },
      {
        id: "verify-gate",
        ownerRoleId: "quality",
        title: text("Verificar prontidão do gate", "Verify gate readiness"),
        detail: text("Confirmar evidências, aprovações e remoção da Rev. B.", "Confirm evidence, approvals, and removal of Rev. B."),
        dependsOn: ["update-electrical", "select-recovery-scenario"],
        sourceIds: ["engineering-standards", "rfi-decisions", "identity-permissions"],
        artifactId: "gate-checklist",
        humanGate: true,
      },
      {
        id: "release-exe-02",
        ownerRoleId: "project-manager",
        title: text("Liberar EXE-02", "Release EXE-02"),
        detail: text("Confirmar prontidão e publicar a decisão coordenada.", "Confirm readiness and publish the coordinated decision."),
        dependsOn: ["verify-gate"],
        sourceIds: ["rfi-decisions", "team-coordination"],
        artifactId: "teams-update",
        humanGate: true,
        managerAction: {
          id: "EXE-02",
          kind: "release",
          label: text("Liberar EXE-02", "Release EXE-02"),
          due: text("18 ago · 17:00", "Aug 18 · 17:00"),
          actionAt: 7,
          blockedLane: "waiting_on_team",
        },
      },
    ],
    handoffStages: [
      { id: "truth", label: text("Verdade controlada", "Controlled truth"), taskIds: ["approve-controlled-truth"] },
      { id: "bim", label: text("Coordenação BIM", "BIM coordination"), taskIds: ["coordinate-bim"] },
      { id: "technical", label: text("Pacotes técnicos", "Technical packages"), taskIds: ["update-electrical", "recover-schedule"] },
      { id: "gate", label: text("Gate verificado", "Verified gate"), taskIds: ["verify-gate"] },
      { id: "release", label: text("Liberação", "Release"), taskIds: ["release-exe-02"] },
    ],
    catalog: [
      {
        id: "coordinate-project-change",
        runCode: "WF-REV-C-001",
        ownerRoleId: "project-manager",
        title: text("Coordenar uma mudança de projeto", "Coordinate a project change"),
        trigger: text("Uma nova revisão chega pelo Slack, Teams ou CDE", "A new revision arrives through Slack, Teams, or the CDE"),
        purpose: text("Compara, localiza dependências e monta um plano integrado", "Compares, finds dependencies, and builds an integrated plan"),
        sourceIds: ["supplier-communication", "controlled-documents", "bim-models", "project-schedule", "team-coordination"],
        agents: [
          { id: "change-agent", name: text("Agente de mudança", "Change agent"), objective: text("Compara revisões e extrai os deltas", "Compares revisions and extracts deltas"), tool: { id: "document-comparison", name: text("Comparador de documentos", "Document comparison"), permission: "read" } },
          { id: "dependency-agent", name: text("Agente de dependências", "Dependency agent"), objective: text("Percorre o grafo das 15 equipes", "Traverses the 15-team graph"), tool: { id: "brain-graph", name: text("Grafo do Brain", "Brain graph"), permission: "query" } },
          { id: "planning-agent", name: text("Agente de planejamento", "Planning agent"), objective: text("Monta responsáveis, datas e critérios", "Builds owners, dates, and criteria"), tool: { id: "planning-sandbox", name: text("Planejador", "Planning sandbox"), permission: "draft" } },
        ],
        gate: {
          taskId: "approve-controlled-truth",
          roleId: "project-manager",
          decision: text("Gerente aprova a nova verdade e os responsáveis", "Manager approves the new truth and owners"),
          evidenceSourceIds: ["supplier-communication", "controlled-documents", "rfi-decisions"],
          affectedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
        },
        outputs: [
          { id: "decision-receipt", label: text("Recibo da decisão", "Decision receipt"), kind: "receipt", recipientRoleIds: ["project-manager", "quality"] },
          { id: "impact-plan", label: text("Plano de impacto", "Impact plan"), kind: "plan", recipientRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"] },
          { id: "role-briefs", label: text("Briefs por função", "Role briefs"), kind: "brief", recipientRoleIds: ["electrical", "bim", "planning", "quality"] },
        ],
        deliveryRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      },
      {
        id: "update-electrical-package",
        runCode: "WF-ELE-008",
        ownerRoleId: "electrical",
        title: text("Atualizar o pacote elétrico", "Update the electrical package"),
        trigger: text("Uma premissa de carga é alterada", "A load assumption changes"),
        purpose: text("Puxa fontes, recalcula carga e prepara marcações do unifilar", "Pulls sources, recalculates load, and prepares single-line markups"),
        sourceIds: ["controlled-documents", "bim-models", "engineering-standards"],
        agents: [
          { id: "load-agent", name: text("Agente de carga", "Load agent"), objective: text("Recalcula demanda e reserva", "Recalculates demand and spare capacity"), tool: { id: "load-calculator", name: text("Calculadora de carga", "Load calculator"), permission: "query" } },
          { id: "standards-agent", name: text("Agente de normas", "Standards agent"), objective: text("Verifica premissas e critérios", "Checks assumptions and criteria"), tool: { id: "revit", name: text("Revit", "Revit"), permission: "read" } },
          { id: "documentation-agent", name: text("Agente de documentação", "Documentation agent"), objective: text("Prepara marcações e memorial", "Prepares markups and calculation note"), tool: { id: "single-line-editor", name: text("Editor de unifilar", "Single-line editor"), permission: "draft" } },
        ],
        gate: {
          taskId: "update-electrical",
          roleId: "electrical",
          decision: text("Líder de Elétrica valida premissas e resultado", "Electrical Lead validates assumptions and result"),
          evidenceSourceIds: ["controlled-documents", "engineering-standards", "bim-models"],
          affectedRoleIds: ["electrical", "bim", "quality"],
        },
        outputs: [
          { id: "electrical-package", label: text("Pacote elétrico Rev. 8", "Electrical package Rev. 8"), kind: "draft", recipientRoleIds: ["electrical", "bim", "quality"] },
        ],
        deliveryRoleIds: ["electrical", "bim", "quality"],
      },
      {
        id: "prepare-bim-coordination",
        runCode: "WF-BIM-014",
        ownerRoleId: "bim",
        title: text("Preparar coordenação BIM", "Prepare BIM coordination"),
        trigger: text("Geometria ou conexão muda", "Geometry or a connection changes"),
        purpose: text("Puxa modelos, cria scaffold básico e identifica interferências", "Pulls models, creates a basic scaffold, and identifies clashes"),
        sourceIds: ["bim-models", "controlled-documents"],
        agents: [
          { id: "model-agent", name: text("Agente de modelos", "Model agent"), objective: text("Localiza e valida as versões corretas", "Finds and validates the correct versions"), tool: { id: "cde", name: text("CDE", "CDE"), permission: "read" } },
          { id: "geometry-agent", name: text("Agente de geometria", "Geometry agent"), objective: text("Cria um scaffold coordenável", "Creates a coordination-ready scaffold"), tool: { id: "revit", name: text("Revit", "Revit"), permission: "draft" } },
          { id: "clash-agent", name: text("Agente de interferências", "Clash agent"), objective: text("Prioriza clashes por impacto", "Prioritizes clashes by impact"), tool: { id: "navisworks", name: text("Navisworks", "Navisworks"), permission: "query" } },
        ],
        gate: {
          taskId: "coordinate-bim",
          roleId: "bim",
          decision: text("Coordenador BIM decide o que entra no modelo federado", "BIM Coordinator decides what enters the federated model"),
          evidenceSourceIds: ["bim-models", "controlled-documents"],
          affectedRoleIds: ["bim", "electrical", "quality"],
        },
        outputs: [
          { id: "bim-scaffold", label: text("Scaffold e relatório de interferências", "Scaffold and clash report"), kind: "draft", recipientRoleIds: ["bim", "electrical", "quality"] },
        ],
        deliveryRoleIds: ["bim", "electrical", "quality"],
      },
      {
        id: "recover-project-schedule",
        runCode: "WF-PLN-021",
        ownerRoleId: "planning",
        title: text("Recuperar o cronograma", "Recover the schedule"),
        trigger: text("Uma data afeta o caminho crítico", "A date affects the critical path"),
        purpose: text("Simula sequências e compara prazo, risco e dependências", "Simulates sequences and compares time, risk, and dependencies"),
        sourceIds: ["project-schedule", "rfi-decisions", "supplier-communication"],
        agents: [
          { id: "critical-path-agent", name: text("Agente de caminho crítico", "Critical-path agent"), objective: text("Rastreia atividades dependentes", "Traces dependent activities"), tool: { id: "primavera-p6", name: text("Primavera P6", "Primavera P6"), permission: "query" } },
          { id: "scenario-agent", name: text("Agente de cenários", "Scenario agent"), objective: text("Testa sequências e sobreposições", "Tests sequences and overlaps"), tool: { id: "scenario-simulator", name: text("Simulador de cenários", "Scenario simulator"), permission: "draft" } },
          { id: "risk-agent", name: text("Agente de risco", "Risk agent"), objective: text("Compara prazo, custo e exposição", "Compares time, cost, and exposure"), tool: { id: "risk-register", name: text("Registro de risco", "Risk register"), permission: "read" } },
        ],
        gate: {
          taskId: "select-recovery-scenario",
          roleId: "project-manager",
          decision: text("Planejamento recomenda; gerente escolhe o cenário", "Planning recommends; the manager selects the scenario"),
          evidenceSourceIds: ["project-schedule", "rfi-decisions"],
          affectedRoleIds: ["project-manager", "planning", "quality"],
        },
        outputs: [
          { id: "recovery-scenarios", label: text("Três cenários de recuperação", "Three recovery scenarios"), kind: "plan", recipientRoleIds: ["project-manager", "planning", "quality"] },
        ],
        deliveryRoleIds: ["project-manager", "planning", "quality"],
      },
      {
        id: "verify-gate-readiness",
        runCode: "WF-QLT-002",
        ownerRoleId: "quality",
        title: text("Verificar prontidão do gate", "Verify gate readiness"),
        trigger: text("Uma liberação está próxima", "A release is approaching"),
        purpose: text("Verifica evidências, aprovações e pendências em todas as equipes", "Checks evidence, approvals, and open items across all teams"),
        sourceIds: ["engineering-standards", "rfi-decisions", "identity-permissions"],
        agents: [
          { id: "evidence-agent", name: text("Agente de evidências", "Evidence agent"), objective: text("Confirma arquivos e aprovações", "Confirms files and approvals"), tool: { id: "evidence-index", name: text("Índice de evidências", "Evidence index"), permission: "read" } },
          { id: "open-item-agent", name: text("Agente de pendências", "Open-item agent"), objective: text("Consolida bloqueios das 15 equipes", "Consolidates blockers across 15 teams"), tool: { id: "gate-validator", name: text("Validador de gates", "Gate validator"), permission: "query" } },
          { id: "audit-agent", name: text("Agente de auditoria", "Audit agent"), objective: text("Monta checklist e recibo rastreável", "Builds the checklist and traceable receipt"), tool: { id: "receipt-generator", name: text("Gerador de recibos", "Receipt generator"), permission: "draft" } },
        ],
        gate: {
          taskId: "verify-gate",
          roleId: "quality",
          decision: text("Qualidade bloqueia ou libera com evidência", "Quality blocks or releases with evidence"),
          evidenceSourceIds: ["engineering-standards", "rfi-decisions", "identity-permissions"],
          affectedRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
        },
        outputs: [
          { id: "exe-02-checklist", label: text("Checklist EXE-02 auditável", "Auditable EXE-02 checklist"), kind: "checklist", recipientRoleIds: ["project-manager", "quality"] },
        ],
        deliveryRoleIds: ["project-manager", "electrical", "bim", "planning", "quality"],
      },
    ],
  },
  story: [
    { step: 0, state: "baseline", stage: text("Projeto sob controle", "Project under control") },
    { step: 1, state: "event_detected", stage: text("Mudança detectada", "Change detected") },
    { step: 2, state: "awaiting_change_approval", stage: text("Verdade em análise", "Truth under review") },
    { step: 3, state: "change_approved", stage: text("Verdade controlada", "Truth controlled") },
    { step: 4, state: "impact_mapping", stage: text("Impacto compreendido", "Impact understood") },
    { step: 5, state: "work_packets_ready", stage: text("Trabalho coordenado", "Work coordinated") },
    { step: 6, state: "execution_in_progress", stage: text("Objetivos em execução", "Objectives in progress") },
    { step: 7, state: "reviews_pending", stage: text("Evidências verificadas", "Evidence verified") },
    { step: 8, state: "release_ready", stage: text("Liberação protegida", "Release protected") },
  ],
});

export function mfText(value, language = "pt") {
  return value[language === "en" ? "en" : "pt"];
}
