"use client";

import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type MfLanguage = "pt" | "en";

const english: Record<string, string> = {
  "Projeto hoje": "Project today",
  "Mudança e aprovação": "Change & approval",
  "Minha equipe": "My team",
  "Trabalhar com Urso": "Work with Urso",
  "Decisões e histórico": "Decisions & history",
  "Abrir Brain e chat": "Open Brain & chat",
  "Seu papel no projeto": "Your project role",
  "Você está trabalhando como": "You are working as",
  "Trocar papel ou equipe": "Switch role or team",
  "Ir para o conteúdo": "Skip to content",
  "Projeto ativo": "Active project",
  "Fase 3": "Phase 3",
  "Projeto executivo": "Executive design",
  "Liberação do projeto executivo": "Executive design release",
  "Etapa": "Stage",
  "Próximo marco": "Next milestone",
  "em risco": "at risk",
  "Risco": "Risk",
  "Visualizar como": "View as",
  "Perguntar ao Urso": "Ask Urso",
  "Disponível após a entrada de um evento": "Available after an event enters the project",
  "Contexto público do projeto. Pessoas, documentos, decisões, prazos e eventos são dados sintéticos de demonstração.":
    "Public project context. People, documents, decisions, schedules, and events are synthetic demonstration data.",
  "Abrir navegação": "Open navigation",
  "Fechar navegação": "Close navigation",
  "Ambiente do projeto": "Project environment",
  "Navegação do projeto": "Project navigation",
  "Torre de controle": "Control tower",
  "Mudanças": "Changes",
  "Disciplinas": "Disciplines",
  "Artefatos": "Artifacts",
  "Cérebro do projeto": "Project Brain",
  "Histórico": "History",
  "Conexões": "Connections",
  "ativo": "live",
  "Cronograma": "Schedule",
  "Controles da demo": "Demo controls",
  "Voltar uma etapa": "Previous step",
  "Reiniciar demonstração": "Reset demonstration",
  "Avançar uma etapa": "Next step",
  "navegar": "navigate",
  "reiniciar": "reset",
  "Atividade do projeto": "Project activity",
  "Atividade recente": "Recent activity",
  "Artefato aprovado": "Artifact approved",
  "receipt registrado": "receipt recorded",
  "AGORA": "NOW",
  "Ver histórico completo": "View complete history",
  "Contexto carregado": "Context loaded",
  "fontes": "sources",
  "disciplinas": "disciplines",
  "Escopo": "Scope",
  "Escopo atual": "Current scope",
  "Fechar assistente": "Close assistant",
  "Respostas usam apenas fontes autorizadas deste projeto.": "Answers use only authorized sources from this project.",
  "Resposta contextual": "Contextual answer",
  "Fontes": "Sources",
  "Pergunta para o Urso": "Question for Urso",
  "Pergunte sobre este projeto…": "Ask about this project…",
  "Enviar pergunta": "Send question",
  "Respostas pré-configuradas para esta demonstração.": "Preconfigured answers for this demonstration.",
  "Modo guiado": "Guided mode",
  "Ocultar guia": "Hide guide",
  "Mostrar guia de apresentação": "Show presentation guide",
  "FALA": "SAY",
  "PROVA": "PROOF",
  "Passo": "Step",
  "AO VIVO": "LIVE",
  "Apresentação ao vivo": "Live presentation",
  "Iniciar apresentação": "Start presentation",
  "Reiniciar apresentação": "Restart presentation",
  "Encerrar apresentação": "End presentation",
  "Cenário de projeto MF × Urso": "MF × Urso project scenario",
  "Aprovar a Revisão C sem perder o marco EXE-02.": "Approve Revision C without missing the EXE-02 milestone.",
  "Acompanhe a revisão desde as fontes autorizadas até a decisão do PM, os pacotes de trabalho e o registro de auditoria.":
    "Trace the revision from authorized sources through the PM decision, work packages, and audit record.",
  "Roteiro da apresentação": "Presentation route",
  "Explorar o sistema": "Explore the system",
  "Prontidão da demonstração": "Demo readiness",
  "Tudo pronto para apresentar.": "Everything is ready to present.",
  "Fixture do projeto": "Project fixture",
  "Carregado": "Loaded",
  "Motor do cenário": "Scenario engine",
  "Idiomas": "Languages",
  "Dependências externas": "External dependencies",
  "Nenhuma": "None",
  "39 docs conectados": "39 connected docs",
  "cenas": "scenes",
  "minutos": "minutes",
  "Setas para navegar": "Arrow keys to navigate",
  "Dados operacionais sintéticos. Contexto controlado conectado.":
    "Synthetic operational data. Connected controlled context.",

  "Baseline aprovado": "Approved baseline",
  "Evento detectado": "Event detected",
  "Aguardando aprovação": "Awaiting approval",
  "Mudança aprovada": "Change approved",
  "Impacto mapeado": "Impact mapped",
  "Pacotes prontos": "Packages ready",
  "Execução em andamento": "Execution in progress",
  "Revisões concluídas": "Reviews completed",
  "Marco pronto": "Milestone ready",
  "Injetar Revisão C": "Inject Revision C",
  "Receber Revisão C": "Receive Revision C",
  "Comparar revisões": "Compare revisions",
  "Aprovar mudança": "Approve change",
  "Mapear impacto": "Map impact",
  "Gerar pacotes de trabalho": "Generate work packages",
  "Executar ferramentas": "Run tools",
  "Concluir revisões humanas": "Complete human reviews",
  "Liberar marco executivo": "Release executive milestone",
  "Demonstração concluída": "Demonstration complete",
  "Baixo": "Low",
  "Baseline coordenada": "Coordinated baseline",
  "Em análise": "Under review",
  "Mudança não aprovada": "Unapproved change",
  "Alto": "High",
  "Gate executivo ameaçado": "Executive gate at risk",
  "Observação": "Watch",
  "Fechamento em verificação": "Closure under verification",
  "Controlado": "Controlled",
  "Evidências completas": "Evidence complete",

  "Fluxo vivo do projeto": "Live project flow",
  "Da mudança à liberação": "From change to release",
  "Monitorando": "Monitoring",
  "Fechado": "Closed",
  "Processando": "Processing",
  "Etapas da mudança": "Change stages",
  "Evidência": "Evidence",
  "Teams · Rev. C": "Teams · Rev. C",
  "Verdade do projeto": "Project truth",
  "Decisão DEC-042": "Decision DEC-042",
  "Dependências": "Dependencies",
  "Execução": "Execution",
  "Pacotes + ferramentas": "Packages + tools",
  "Liberação": "Release",
  "Aguardando": "Waiting",
  "10 disciplinas acionadas": "10 disciplines activated",
  "Mapa de impacto aguardando decisão": "Impact map awaiting decision",
  "5 críticas · 3 em observação · 2 de suporte": "5 critical · 3 watch · 2 support",
  "A conversa ainda não altera o plano aprovado": "The conversation has not changed the approved plan",

  "Contexto público verificado": "Verified public context",
  "Projeto e gerenciamento de obra para expansão da fábrica de envase.":
    "Design and construction management for the bottling-plant expansion.",
  "49.350 m² de área": "49,350 m² area",
  "80.000 garrafas/hora": "80,000 bottles/hour",
  "+69% de produção": "+69% production",
  "Projeto, gerenciamento e fiscalização MF": "MF design, management, and inspection",
  "Fonte oficial MF": "Official MF source",
  "O cenário operacional abaixo é sintético.": "The operational scenario below is synthetic.",

  "O projeto, coordenado em tempo real.": "The project, coordinated in real time.",
  "Uma visão operacional da verdade aprovada, do trabalho em curso e do que ainda impede a liberação.":
    "An operational view of approved truth, work in progress, and what still blocks release.",
  "Marco liberado": "Milestone released",
  "Indicadores do projeto": "Project indicators",
  "Risco do marco": "Milestone risk",
  "Prontidão executiva": "Executive readiness",
  "Gate completo": "Gate complete",
  "Evidências ponderadas": "Weighted evidence",
  "Disciplinas afetadas": "Affected disciplines",
  "Com ação ou revisão": "With action or review",
  "Aguardando decisão": "Awaiting decision",
  "Janela do marco": "Milestone window",
  "Janela econômica de mudança": "Low-cost change window",
  "Marco protegido": "Milestone protected",
  "Fechando": "Closing",
  "Aberta": "Open",
  "Decidir antes da execução mantém o custo da mudança baixo.":
    "Deciding before field execution keeps the cost of change low.",
  "Horizonte de decisão do projeto": "Project decision horizon",
  "Agora": "Now",
  "Coordenação digital": "Digital coordination",
  "Limite de decisão": "Decision cutoff",
  "Custo elevado": "High cost",
  "Tempo protegido": "Protected time",
  "Após impacto confirmado": "After confirmed impact",
  "Coordenação integrada": "Integrated coordination",
  "15 disciplinas, uma verdade": "15 disciplines, one truth",
  "Abrir mapa": "Open map",
  "Gate EXE-02": "Gate EXE-02",
  "Prontidão de liberação": "Release readiness",
  "Premissa vigente aprovada": "Current assumption approved",
  "Pacotes disciplinares emitidos": "Discipline packages issued",
  "Revisões técnicas concluídas": "Technical reviews completed",
  "Evidência de gate completa": "Gate evidence complete",
  "Estável": "Stable",
  "Ação crítica": "Critical action",
  "Revisão": "Review",
  "Verificação": "Verification",
  "Sem impacto": "No impact",

  "Mudanças do projeto": "Project changes",
  "Nenhuma alteração material em aberto.": "No material changes are open.",
  "Urso monitora os canais autorizados sem transformar conversas em verdade oficial.":
    "Urso monitors authorized channels without turning conversations into official truth.",
  "Monitoramento ativo": "Active monitoring",
  "O baseline permanece vigente. A fonte, o comparativo e o plano de impacto só aparecem quando um novo evento entra no projeto.":
    "The baseline remains current. The source, comparison, and impact plan appear only when a new event enters the project.",
  "Mudança CHG-024": "Change CHG-024",
  "Revisão C da linha de envase": "Bottling line Revision C",
  "Da conversa original à decisão controlada e ao plano de resposta multidisciplinar.":
    "From the original conversation to a controlled decision and multidisciplinary response plan.",
  "Ver execução": "View execution",
  "Hoje, 09:42 · Engenheiro de Processo": "Today, 09:42 · Process Engineer",
  "Recebemos a revisão final do fornecedor. A linha ficou 1,2 m maior, com aumento de carga e demanda de água gelada. A entrega também passou para D+10. Favor verificar impacto.":
    "We received the supplier's final revision. The line is 1.2 m longer, with higher electrical load and chilled-water demand. Delivery also moved to D+10. Please assess the impact.",
  "A mensagem foi preservada como origem. Ela só altera a verdade do projeto após aprovação.":
    "The message is preserved as source evidence. It changes project truth only after approval.",
  "Estado da verdade": "Truth state",
  "Revisão C vigente": "Revision C current",
  "Mudança proposta": "Proposed change",
  "DEC-042 aprovada pelo Gerente do Projeto às 09:47.": "DEC-042 approved by the Project Manager at 09:47.",
  "A análise está pronta, mas nenhuma premissa foi alterada silenciosamente.":
    "The analysis is ready, but no assumption was changed silently.",
  "Versão anterior": "Previous version",
  "Responsável": "Owner",
  "Registro": "Record",
  "Pendente": "Pending",
  "Comparativo controlado": "Controlled comparison",
  "O que mudou entre B e C": "What changed between B and C",
  "4 diferenças materiais": "4 material differences",
  "Envelope do equipamento": "Equipment envelope",
  "Layout e clearances": "Layout and clearances",
  "Carga elétrica": "Electrical load",
  "Alimentador e unifilar": "Feeder and single-line diagram",
  "Água gelada": "Chilled water",
  "Balanço térmico e vazão": "Thermal balance and flow",
  "Entrega do fornecedor": "Supplier delivery",
  "Caminho crítico": "Critical path",
  "Plano de resposta": "Response plan",
  "Impacto multidisciplinar": "Multidisciplinary impact",
  "Aprovação registrada · impacto ainda não mapeado": "Approval recorded · impact not yet mapped",
  "Aguardando aprovação para propagar": "Awaiting approval before propagation",
  "10 ações": "10 actions",
  "A decisão está registrada. O mapeamento ainda precisa ser executado para criar trabalho.":
    "The decision is recorded. Impact mapping must still run before work is created.",
  "Urso não distribui trabalho com base em uma conversa não aprovada.":
    "Urso does not distribute work from an unapproved conversation.",

  "Coordenação multidisciplinar": "Multidisciplinary coordination",
  "Um plano. Quinze perspectivas.": "One plan. Fifteen perspectives.",
  "Cada equipe vê somente o que mudou, por quê, sua ação e o critério de conclusão.":
    "Each team sees only what changed, why it matters, its action, and the completion criterion.",
  "Abrir harness": "Open harness",
  "Cérebro e governança": "Brain and governance",
  "Decisão, coordenação e controle": "Decision, coordination, and control",
  "Esqueleto": "Skeleton",
  "Base física e estrutural": "Physical and structural foundation",
  "Órgãos e sistemas": "Organs and systems",
  "Utilidades e sistemas operacionais": "Utilities and operating systems",
  "Workspace contextual": "Contextual workspace",
  "Pacote disponível": "Package available",
  "Aguardando coordenação": "Awaiting coordination",
  "O que importa agora": "What matters now",
  "Evidências carregadas": "Loaded evidence",
  "Entregável esperado": "Expected deliverable",
  "Aguardando execução": "Awaiting execution",
  "Aprovado · receipt registrado": "Approved · receipt recorded",
  "Validado · aguarda responsável": "Validated · awaiting owner",
  "Gerado · aguardando validação": "Generated · awaiting validation",
  "Disponível após execução": "Available after execution",
  "Abrir pacote de trabalho": "Open work package",

  "Execução durável, não uma resposta de chat.": "Durable execution, not a chat response.",
  "Cada passo preserva o método, a fonte, o resultado e quem tem autoridade para aprovar.":
    "Each step preserves the method, source, result, and approval authority.",
  "Concluir execução": "Complete execution",
  "Liberar gate": "Release gate",
  "Run atual": "Current run",
  "Resposta coordenada à Revisão C": "Coordinated response to Revision C",
  "Humano": "Human",
  "Agente": "Agent",
  "Determinístico": "Deterministic",
  "Contrato de execução": "Execution contract",
  "Controles ativos": "Active controls",
  "Fonte autorizada": "Authorized source",
  "Procedimento versionado": "Versioned procedure",
  "Aprovação humana material": "Material human approval",
  "Dependências registradas": "Recorded dependencies",
  "Passos concluídos": "Completed steps",
  "Ver artefatos": "View artifacts",

  "Artefatos controlados": "Controlled artifacts",
  "O sistema produz trabalho verificável.": "The system produces verifiable work.",
  "Todo rascunho mantém fontes, versão do procedimento, validação e responsável técnico.":
    "Every draft retains its sources, procedure version, validation, and technical owner.",
  "Concluir revisões": "Complete reviews",
  "Rascunho": "Draft",
  "Validado": "Validated",
  "Aprovado": "Approved",
  "Bloqueado": "Blocked",
  "Aguardando workflow": "Awaiting workflow",
  "Abrir artefato": "Open artifact",
  "Execução assistida · BIM": "Assisted execution · BIM",
  "Scaffold conceitual da linha": "Conceptual line scaffold",
  "Demonstração": "Demonstration",
  "Este artefato organiza geometria, conexões e zonas de revisão para a equipe. Não substitui o modelo técnico nem pode ser usado para construção.":
    "This artifact organizes geometry, connections, and review zones for the team. It does not replace the technical model and cannot be used for construction.",
  "Ver trilha": "View trail",
  "artefatos disponíveis nesta etapa.": "artifacts available at this stage.",

  "Não guarda arquivos. Mantém relações operacionais.": "It does not store files. It maintains operational relationships.",
  "Fonte, premissa, decisão, trabalho e liberação permanecem conectados e explicáveis.":
    "Source, assumption, decision, work, and release remain connected and explainable.",
  "Abrir histórico": "Open history",
  "relações ativas": "active relationships",
  "Filtrar estado da verdade": "Filter truth state",
  "Vigente": "Current",
  "Com histórico": "With history",
  "Premissa": "Assumption",
  "Decisão": "Decision",
  "Mudança": "Change",
  "Disciplina": "Discipline",
  "Artefato": "Artifact",
  "Aprovação": "Approval",
  "Marco": "Milestone",
  "Grafo de execução do projeto": "Project execution graph",
  "Premissa vigente": "Current assumption",
  "Verdade operacional": "Operational truth",
  "Histórico de versões": "Version history",
  "Proposta": "Proposed",
  "Por que essa relação existe?": "Why does this relationship exist?",
  "Aguardando novo evento": "Awaiting a new event",
  "A baseline está sincronizada. Selecione uma relação conforme o cenário avança para inspecionar sua causa e evidência.":
    "The baseline is synchronized. Select a relationship as the scenario advances to inspect its cause and evidence.",
  "Baseline Rev. 12 · sincronizada 08:20": "Baseline Rev. 12 · synchronized 08:20",
  "Teams → evidência preservada": "Teams → preserved evidence",
  "A mensagem e o anexo entram como evidência candidata. O Brain preserva origem, horário e hash sem alterar a baseline do projeto.":
    "The message and attachment enter as candidate evidence. The Brain preserves source, time, and hash without changing the project baseline.",
  "Rev. C → quatro deltas materiais": "Rev. C → four material deltas",
  "O comparador reconciliou envelope, carga elétrica, demanda de água gelada e entrega com os campos equivalentes da Revisão B.":
    "The comparator reconciled envelope, electrical load, chilled-water demand, and delivery against the equivalent Revision B fields.",
  "Aprovação humana → verdade vigente": "Human approval → current truth",
  "A DEC-042 torna a Revisão C vigente. A Revisão B continua rastreável, mas deixa de orientar qualquer novo entregável.":
    "DEC-042 makes Revision C current. Revision B remains traceable but no longer guides new deliverables.",
  "DEC-042 → mudança controlada": "DEC-042 → controlled change",
  "A decisão abre uma mudança formal com escopo, responsáveis, critérios de fechamento e vínculo ao marco executivo.":
    "The decision opens a formal change with scope, owners, closure criteria, and a link to the executive milestone.",
  "Rev. C → Elétrica": "Rev. C → Electrical",
  "A potência instalada alimenta a lista de cargas. O aumento de 15% pode alterar o alimentador, o unifilar, a bandeja e a coordenação BIM.":
    "Installed power feeds the load list. The 15% increase may change the feeder, single-line diagram, tray occupancy, and BIM coordination.",
  "Impacto → trabalho executável": "Impact → executable work",
  "Cada impacto é convertido em um pacote com entrada aprovada, ferramenta permitida, responsável técnico, saída esperada e critério de aceitação.":
    "Each impact becomes a package with approved input, allowed tool, technical owner, expected output, and acceptance criterion.",
  "Artefato → receipt de aprovação": "Artifact → approval receipt",
  "Validações automáticas verificam consistência; a autoridade disciplinar aceita, corrige ou bloqueia o resultado antes de ele atualizar o projeto.":
    "Automated validations check consistency; the discipline authority accepts, corrects, or blocks the result before it updates the project.",
  "Evidência completa → liberação": "Complete evidence → release",
  "O gate só muda para pronto quando decisões, pacotes, aprovações e dependências possuem evidência verificável e nenhuma pendência crítica permanece.":
    "The gate becomes ready only when decisions, packages, approvals, and dependencies have verifiable evidence and no critical issue remains.",

  "Histórico auditável": "Auditable history",
  "Cada mudança deixa um recibo.": "Every change leaves a receipt.",
  "Quem agiu, com qual fonte, sob qual procedimento e qual estado foi produzido.":
    "Who acted, with which source, under which procedure, and what state was produced.",
  "Ver relações": "View relationships",
  "Horário": "Time",
  "Evento": "Event",
  "Ator / sistema": "Actor / system",
  "Recibo": "Receipt",
  "aprovado": "approved",
  "Validações concluídas · Brain e dependências atualizados": "Validations completed · Brain and dependencies updated",
  "Procedimento": "Procedure",
  "Aprovação material": "Material approval",
  "confirmada": "confirmed",
  "Artefatos aprovados": "Approved artifacts",
  "cadeia completa": "complete chain",
  "em construção": "in progress",

  "Rascunho gerado": "Draft generated",
  "Aprovado para o projeto": "Approved for the project",
  "Fechar artefato": "Close artifact",
  "Fechar resultado": "Close result",
  "Contexto autorizado": "Authorized context",
  "Fontes carregadas": "Loaded sources",
  "Vigente · hash verificado": "Current · hash verified",
  "Execução isolada · demo": "Isolated execution · demo",
  "Saída controlada": "Controlled output",
  "Prévia do artefato": "Artifact preview",
  "Trabalho produzido": "Work produced",
  "Prévia do resultado": "Result preview",
  "Harness + governança": "Harness + governance",
  "Revisão técnica": "Technical review",
  "entradas verificadas": "inputs verified",
  "Rascunho produzido": "Draft produced",
  "Ferramenta isolada concluída": "Isolated tool completed",
  "Validadores": "Validators",
  "Aprovação humana": "Human approval",
  "Executar validadores": "Run validators",
  "Aprovar rascunho": "Approve draft",
  "Solicitar correção": "Request correction",
  "Aprovação registrada": "Approval recorded",
  "Próxima ação": "Next action",
  "Atualizar o Brain e equipes dependentes": "Update the Brain and dependent teams",
  "Comparação semântica · B → C": "Semantic comparison · B → C",
  "Campo": "Field",
  "Comprimento": "Length",
  "Carga instalada": "Installed load",
  "Entrega": "Delivery",
  "Quatro mudanças materiais reconciliadas com as seções de origem.":
    "Four material changes reconciled against source sections.",
  "Revisão de alimentador": "Feeder review",
  "Balanço de água gelada": "Chilled-water balance",
  "ENTRADA APROVADA": "APPROVED INPUT",
  "Resultado produzido em ambiente isolado. O responsável técnico deve verificar premissas e selecionar a solução final.":
    "Result produced in an isolated environment. The technical owner must verify assumptions and select the final solution.",
  "Scaffold conceitual · não construtivo": "Conceptual scaffold · not for construction",
  "Cenário": "Scenario",
  "Recuperação": "Recovery",
  "Risco técnico": "Technical risk",
  "Rejeitar": "Reject",
  "Recomendado": "Recommended",
  "Reserva": "Fallback",
  "Cenário B protege as aprovações técnicas e recupera oito dias.":
    "Scenario B protects technical approvals and recovers eight days.",
  "Conforme": "Compliant",
  "Confirmação do Gerente do Projeto": "Project Manager confirmation",
  "Etapa final do gate": "Final gate step",
  "Rascunho · não publicado": "Draft · not published",
  "Revisão C aprovada e plano coordenado": "Revision C approved and plan coordinated",
  "A DEC-042 substitui a Rev. B. Dez disciplinas receberam ações; Elétrica, HVAC, BIM, Estruturas de Concreto e Planejamento estão no caminho crítico. Consulte os pacotes vinculados antes de emitir novos documentos.":
    "DEC-042 supersedes Rev. B. Ten disciplines received actions; Electrical, HVAC, BIM, Concrete Structures, and Planning are on the critical path. Review linked packages before issuing new documents.",
  "Ações críticas": "Critical actions",
  "Revisões": "Reviews",
  "Verificações": "Checks",
  "Owner e critério vinculados": "Owner and criterion linked",

  "Gerente do Projeto": "Project Manager",
  "Líder de Elétrica": "Electrical Lead",
  "Coordenador BIM": "BIM Coordinator",
  "Engenheiro de Planejamento": "Planning Engineer",
  "Líder de Qualidade": "Quality Lead",
  "Planejamento e Controle": "Planning & Control",
  "Qualidade": "Quality",
  "Metodologia BIM": "BIM Methodology",
  "Arquitetura": "Architecture",
  "Infraestrutura": "Infrastructure",
  "Estruturas de Concreto": "Concrete Structures",
  "Estruturas Metálicas": "Steel Structures",
  "Hidráulica": "Hydraulics",
  "Elétrica": "Electrical",
  "Mecânica e Tubulação": "Mechanical & Piping",
  "Sistemas Especiais e Automação": "Special Systems & Automation",
  "Proteção Contra Incêndio": "Fire Protection",
  "Viabilidade": "Viability",
  "Líder de Viabilidade": "Viability Lead",
  "Coordenador de BID": "BID Coordinator",
  "Engenheiro Estrutural": "Structural Engineer",
  "Líder de Arquitetura": "Architecture Lead",
  "Líder de Infraestrutura": "Infrastructure Lead",
  "Líder de Estruturas Metálicas": "Steel Structures Lead",
  "Líder de Hidráulica": "Hydraulics Lead",
  "Líder de HVAC": "HVAC Lead",
  "Líder de Mecânica": "Mechanical Lead",
  "Líder de Automação": "Automation Lead",
  "Líder de Incêndio": "Fire Protection Lead",
  "Coordenação BIM": "BIM Coordination",
  "Coordenação do Projeto": "Project Coordination",
  "Gerenciamento do Projeto": "Project Management",
  "Análise documental": "Document analysis",
  "Coordenação": "Coordination",
  "Pacote disciplinar": "Discipline package",
  "Modelo de apoio": "Support model",
  "Planejamento": "Planning",
  "Comunicação operacional": "Operational communication",
  "Comparativo Rev. B × Rev. C": "Revision B × Revision C comparison",
  "Plano de impacto integrado": "Integrated impact plan",
  "Pacote elétrico Rev. 8": "Electrical package Rev. 8",
  "Pacote HVAC Rev. 6": "HVAC package Rev. 6",
  "Scaffold BIM conceitual": "Conceptual BIM scaffold",
  "Opções de recuperação do marco": "Milestone recovery options",
  "Checklist de prontidão EXE-02": "EXE-02 readiness checklist",
  "Atualização coordenada para o Teams": "Coordinated Teams update",
  "Disponível na etapa 7.": "Available at stage 7.",
  "Avançar cenário": "Advance scenario",
  "dias": "days",
  "pronto": "ready",
  "Interferência": "Clash",
  "Fontes autorizadas": "Authorized sources",
  "Recebido": "Received",
  "Elevado": "Elevated",
  "A · absorver atraso": "A · absorb delay",
  "B · revisão paralela": "B · parallel review",
  "C · compressão total": "C · full compression",
  "Projeto / Coordenação Geral": "Project / General Coordination",
  "Emitida em 22 jul · aprovada": "Issued Jul 22 · approved",
  "Recebida hoje · fonte preservada": "Received today · source preserved",
  "Fonte": "Source",
  "Equipamento / processo": "Equipment / process",
  "Elétrica · HVAC · BIM +7": "Electrical · HVAC · BIM +7",
  "Pacotes coordenados": "Coordinated packages",
  "Revisões técnicas": "Technical reviews",

  "Fechar a mudança sem perder o marco executivo.": "Close the change without losing the executive milestone.",
  "Aprovar donos, prazos e critérios de fechamento do plano integrado.":
    "Approve owners, deadlines, and closure criteria for the integrated plan.",
  "Revisão C aprovada": "Revision C approved",
  "Matriz de impacto": "Impact matrix",
  "Decisão coordenada de liberação": "Coordinated release decision",
  "Absorver o aumento de 15% da carga instalada.": "Absorb the 15% increase in installed load.",
  "Atualizar lista de cargas, alimentador e unifilar; devolver para revisão BIM.":
    "Update the load list, feeder, and single-line diagram; return them for BIM review.",
  "Lista de cargas Rev. 7": "Load List Rev. 7",
  "Pacote elétrico Rev. 8 — rascunho": "Electrical package Rev. 8 — draft",
  "Reconciliar o footprint revisado com o modelo federado.": "Reconcile the revised footprint with the federated model.",
  "Gerar scaffold, reposicionar conexões e validar zonas de interferência.":
    "Generate the scaffold, reposition connections, and validate clash zones.",
  "Layout Rev. 4": "Layout Rev. 4",
  "Scaffold BIM conceitual — rascunho": "Conceptual BIM scaffold — draft",
  "Recuperar o atraso de 10 dias sem mascarar dependências.": "Recover the 10-day delay without hiding dependencies.",
  "Simular recuperação, sequenciamento e nova folga do gate executivo.":
    "Simulate recovery, sequencing, and the executive gate's new float.",
  "Cronograma base Rev. 12": "Baseline Schedule Rev. 12",
  "Log do fornecedor": "Supplier log",
  "Dependências de revisão": "Review dependencies",
  "Opções de recuperação — para decisão": "Recovery options — for decision",
  "Garantir que nenhuma disciplina libere premissas antigas.": "Ensure no discipline releases outdated assumptions.",
  "Verificar seis aprovações e evidências antes de desbloquear o gate.":
    "Verify six approvals and their evidence before unlocking the gate.",
  "Checklist Gate EXE-02": "Gate EXE-02 checklist",
  "Registro de aprovações": "Approval record",
  "Mapa de supersessão": "Supersession map",
  "Parecer de prontidão do gate": "Gate readiness opinion",

  "Evento recebido do Slack": "Event received from Slack",
  "Mensagem e anexo preservados como evidência; ainda não são verdade oficial.":
    "Message and attachment preserved as evidence; they are not yet official truth.",
  "Revisões B e C comparadas": "Revisions B and C compared",
  "Quatro diferenças materiais extraídas com referência à fonte.": "Four material differences extracted with source references.",
  "Gerente do Projeto confirmou a Rev. C como premissa vigente.":
    "The Project Manager confirmed Rev. C as the current assumption.",
  "Dependências mapeadas": "Dependencies mapped",
  "Quinze disciplinas avaliadas; dez exigem ação ou verificação.":
    "Fifteen disciplines assessed; ten require action or verification.",
  "Pacotes de trabalho montados": "Work packages assembled",
  "Insumos, fontes, critérios, donos e entregáveis agrupados por disciplina.":
    "Inputs, sources, criteria, owners, and deliverables grouped by discipline.",
  "Ferramentas de execução iniciadas": "Execution tools started",
  "Cálculos, scaffold BIM, cenário de prazo e validações executados em sandbox.":
    "Calculations, BIM scaffold, schedule scenario, and validations executed in a sandbox.",
  "Revisões humanas registradas": "Human reviews recorded",
  "Responsáveis técnicos aceitaram, corrigiram ou bloquearam os rascunhos.":
    "Technical owners accepted, corrected, or blocked the drafts.",
  "Gate liberado": "Gate released",
  "Evidências completas, dependências fechadas e pacote pronto para emissão.":
    "Evidence complete, dependencies closed, and package ready for issue.",

  "Footprint, carga, água gelada e prazo com trechos de origem vinculados.":
    "Footprint, load, chilled water, and schedule with linked source excerpts.",
  "4 diferenças verificadas": "4 differences verified",
  "Ações, dependências, responsáveis e critérios de fechamento para 15 disciplinas.":
    "Actions, dependencies, owners, and closure criteria for 15 disciplines.",
  "15 disciplinas avaliadas": "15 disciplines assessed",
  "Lista de cargas, alimentador e unifilar preparados para o aumento de potência da linha.":
    "Load list, feeder, and single-line diagram prepared for the line's power increase.",
  "Carga e alimentador recalculados": "Load and feeder recalculated",
  "Balanço térmico, vazão e conexão revisados para o aumento de água gelada.":
    "Thermal balance, flow, and connection revised for the increased chilled-water demand.",
  "Balanço e vazão reconciliados": "Balance and flow reconciled",
  "Envelope antes/depois, conexões, clearances e zonas de roteamento afetadas.":
    "Before/after envelope, connections, clearances, and affected routing zones.",
  "2 interferências para revisão": "2 clashes for review",
  "Três cenários comparados por prazo, risco técnico e dependências críticas.":
    "Three scenarios compared by schedule, technical risk, and critical dependencies.",
  "Evidências e aprovações requeridas antes da liberação executiva.":
    "Evidence and approvals required before executive release.",
  "6 de 6 revisões concluídas": "6 of 6 reviews completed",
  "Resumo de decisão, ações por disciplina, prazos e links para os novos pacotes.":
    "Decision summary, actions by discipline, deadlines, and links to new packages.",
  "Destinatários e links verificados": "Recipients and links verified",

  "Baseline sincronizada": "Baseline synchronized",
  "Gate executivo em 14 dias; risco baixo.": "Executive gate in 14 days; low risk.",
  "Revisão C detectada": "Revision C detected",
  "Mudança material proposta": "Material change proposed",
  "4 diferenças requerem aprovação.": "4 differences require approval.",
  "Rev. C aprovada": "Rev. C approved",
  "Rev. B preservada como superseded.": "Rev. B preserved as superseded.",
  "Impacto propagado": "Impact propagated",
  "10 disciplinas exigem ação ou revisão.": "10 disciplines require action or review.",
  "Pacotes distribuídos": "Packages distributed",
  "Donos e critérios enviados ao projeto.": "Owners and criteria sent to the project.",
  "Ferramentas concluídas": "Tools completed",
  "8 artefatos aguardam revisão humana.": "8 artifacts await human review.",
  "Gate pronto para verificação final.": "Gate ready for final verification.",
  "Marco pronto para liberação": "Milestone ready for release",
  "Trilha de evidência completa.": "Evidence trail complete.",

  "Por que o risco do projeto mudou?": "Why did project risk change?",
  "O que está bloqueando Elétrica?": "What is blocking Electrical?",
  "Qual documento está aprovado agora?": "Which document is approved now?",
  "O que falta para liberar o projeto executivo?": "What remains before executive design can be released?",
  "A Revisão C alterou quatro premissas. O atraso de 10 dias cruza o caminho crítico; o aumento de 15% da carga e 18% da água gelada bloqueia a liberação até Elétrica, HVAC, BIM e Qualidade concluírem suas revisões.":
    "Revision C changed four assumptions. The 10-day delay crosses the critical path; the 15% load increase and 18% chilled-water increase block release until Electrical, HVAC, BIM, and Quality complete their reviews.",
  "A lista de cargas ainda usa a potência da Revisão B. Elétrica precisa validar o alimentador revisado e devolver o unifilar para coordenação BIM antes do gate EXE-02.":
    "The load list still uses Revision B power. Electrical must validate the revised feeder and return the single-line diagram for BIM coordination before gate EXE-02.",
  "Filling Line Data Sheet — Revisão C é a versão vigente desde 09:47. A Revisão B foi preservada no histórico como superseded e não deve orientar novos entregáveis.":
    "Filling Line Data Sheet — Revision C has been current since 09:47. Revision B is preserved in history as superseded and must not guide new deliverables.",
  "Faltam as revisões técnicas dos quatro artefatos gerados, o fechamento das duas interferências BIM e a confirmação do plano de recuperação pelo Gerente do Projeto.":
    "The remaining work is technical review of the generated artifacts, closure of two BIM clashes, and Project Manager confirmation of the recovery plan.",
  "A Revisão B continua vigente. A Revisão C foi preservada como evidência e comparada, mas permanece proposta até o Gerente do Projeto registrar a decisão.":
    "Revision B remains current. Revision C is preserved and compared as evidence, but remains proposed until the Project Manager records the decision.",
  "O aumento de 15% da carga foi identificado, mas o pacote elétrico ainda não existe. Primeiro a mudança precisa ser aprovada e o impacto propagado para Elétrica.":
    "The 15% load increase has been identified, but the electrical package does not exist yet. The change must first be approved and propagated to Electrical.",
  "Ainda faltam o plano de impacto, os pacotes por disciplina, a execução das ferramentas, as aprovações técnicas e a verificação final do gate.":
    "The impact plan, discipline packages, tool execution, technical approvals, and final gate verification are still outstanding.",
  "Os pacotes já foram distribuídos. Faltam executar ou validar os oito artefatos, fechar duas interferências BIM e confirmar o plano de recuperação.":
    "The packages are distributed. The eight artifacts must be executed or validated, two BIM clashes closed, and the recovery plan confirmed.",
  "Nada crítico permanece aberto. O gate EXE-02 possui decisões, artefatos, aprovações e evidências completas e está pronto para liberação.":
    "No critical issue remains open. Gate EXE-02 has complete decisions, artifacts, approvals, and evidence and is ready for release.",
  "Data Sheet Rev. C §§2.1, 4.2 e 5.4 · Cronograma Rev. 12":
    "Data Sheet Rev. C §§2.1, 4.2 and 5.4 · Schedule Rev. 12",
  "Pacote ELE-08 · Premissa EL-014 · Checklist EXE-02":
    "Package ELE-08 · Assumption EL-014 · Checklist EXE-02",
  "Registro de decisão DEC-042 · Histórico de versões": "Decision record DEC-042 · Version history",
  "Gate EXE-02 · Workflow WF-REV-C-001": "Gate EXE-02 · Workflow WF-REV-C-001",
  "Histórico de versões · Mudança proposta CHG-024": "Version history · Proposed change CHG-024",
  "Data Sheet Rev. C §4.2 · Estado atual do WF-REV-C-001": "Data Sheet Rev. C §4.2 · Current WF-REV-C-001 state",
  "Gate EXE-02 · Estado atual do WF-REV-C-001": "Gate EXE-02 · Current WF-REV-C-001 state",
  "Checklist EXE-02 · Histórico de receipts · WF-REV-C-001": "Checklist EXE-02 · Receipt history · WF-REV-C-001",
  "Pacotes disciplinares · Gate EXE-02 · WF-REV-C-001": "Discipline packages · Gate EXE-02 · WF-REV-C-001",

  "Nenhuma alteração de viabilidade confirmada nesta etapa.": "No viability change is confirmed at this stage.",
  "Nenhum efeito contratual confirmado nesta etapa.": "No contractual effect is confirmed at this stage.",
  "Atraso de 10 dias ameaça o marco de liberação executiva.": "A 10-day delay threatens the executive release milestone.",
  "O gate exige evidência de revisão das disciplinas afetadas.": "The gate requires review evidence from affected disciplines.",
  "Footprint e pontos de conexão exigem nova coordenação federada.": "The footprint and connection points require new federated coordination.",
  "O novo envelope reduz a faixa de circulação adjacente.": "The new envelope reduces the adjacent circulation zone.",
  "Rotas externas permanecem estáveis nesta revisão.": "External routes remain stable in this revision.",
  "Base do equipamento depende da nova geometria e carga confirmada.": "The equipment base depends on the new geometry and confirmed load.",
  "Nenhum suporte metálico afetado foi identificado.": "No affected steel support has been identified.",
  "Sem alteração de consumo sanitário ou drenagem confirmada.": "No confirmed change to sanitary consumption or drainage.",
  "Demanda de água gelada aumentou 18%.": "Chilled-water demand increased by 18%.",
  "Carga instalada da linha aumentou 15%.": "The line's installed load increased by 15%.",
  "Conexões e rotas devem acompanhar o deslocamento de 1,2 m.": "Connections and routes must follow the 1.2 m shift.",
  "A nova revisão pode alterar pontos de I/O e intertravamentos.": "The new revision may change I/O points and interlocks.",
  "Novo envelope requer revisão de cobertura e rota de fuga.": "The new envelope requires a coverage and escape-route review.",
  "Teams · Projeto / Engenharia de Processo": "Teams · Project / Process Engineering",
  "Rev. C · 2,4 MB · SHA preservado": "Rev. C · 2.4 MB · SHA preserved",
  "vigente": "current",
  "auditável": "auditable",
  "+1,2 m": "+1.2 m",
  "+10 dias": "+10 days",
  "Comparação do envelope da linha de envase antes e depois da Revisão C, com conexões e zonas de interferência.":
    "Comparison of the bottling-line envelope before and after Revision C, with connections and clash zones.",
  "+1,2 m · envelope revisado": "+1.2 m · revised envelope",
  "Interferência 02": "Clash 02",
  "Conexão HVAC": "HVAC connection",
  "DEMONSTRAÇÃO · NÃO CONSTRUTIVO": "DEMONSTRATION · NOT FOR CONSTRUCTION",
  "Lista de Cargas Rev. 7": "Load List Rev. 7",
  "Premissa EL-014": "Assumption EL-014",
  "Demanda do painel: 812 → 908 kVA": "Panel demand: 812 → 908 kVA",
  "Reserva atual abaixo do limite MF": "Current reserve below the MF limit",
  "Confirmar alimentador 4×240 mm²": "Confirm 4×240 mm² feeder",
  "Registro do fornecedor SUP-118": "Supplier record SUP-118",
  "Envelope +1,2 m": "Envelope +1.2 m",
  "Carga elétrica +15%": "Electrical load +15%",
  "Água gelada +18%": "Chilled water +18%",
  "Entrega +10 dias": "Delivery +10 days",
  "Confirmar mudança material": "Confirm material change",
  "Preservar Rev. B como superseded": "Preserve Rev. B as superseded",
  "Propagar premissas aprovadas": "Propagate approved assumptions",
  "Matriz de dependências": "Dependency matrix",
  "Plano executivo EXE-02": "Executive plan EXE-02",
  "5 ações críticas": "5 critical actions",
  "3 revisões técnicas": "3 technical reviews",
  "2 verificações": "2 checks",
  "5 disciplinas estáveis": "5 stable disciplines",
  "Designar responsáveis": "Assign owners",
  "Definir critérios de fechamento": "Define closure criteria",
  "Monitorar bloqueios do gate": "Monitor gate blockers",
  "Atualizar diagrama unifilar": "Update single-line diagram",
  "Devolver ocupação para coordenação BIM": "Return occupancy data to BIM coordination",
  "Memória HVAC Rev. 5": "HVAC Calculation Report Rev. 5",
  "Vazão: 20,1 → 23,7 l/s": "Flow: 20.1 → 23.7 l/s",
  "Chiller mantém 8% de reserva": "Chiller retains 8% reserve",
  "Atualizar memória de cálculo": "Update calculation report",
  "Revisar válvula de controle": "Review control valve",
  "Coordenar nova conexão com Mecânica": "Coordinate new connection with Mechanical",
  "Envelope deslocado 1,2 m": "Envelope shifted 1.2 m",
  "Clearance sul reduzido": "Reduced south clearance",
  "Duas interferências de utilidades": "Two utility clashes",
  "Reposicionar conexões": "Reposition connections",
  "Revisar faixa de manutenção": "Review maintenance zone",
  "Emitir modelo federado para coordenação": "Issue federated model for coordination",
  "Cronograma Base Rev. 12": "Baseline Schedule Rev. 12",
  "Cenário A mantém atraso de 10 dias": "Scenario A retains the 10-day delay",
  "Cenário C recupera 10 dias com alto risco": "Scenario C recovers 10 days with high risk",
  "Selecionar cenário B": "Select scenario B",
  "Antecipar revisão interdisciplinar": "Bring forward interdisciplinary review",
  "Proteger folga do gate EXE-02": "Protect gate EXE-02 float",
  "Receipts do workflow": "Workflow receipts",
  "6 aprovações técnicas presentes": "6 technical approvals present",
  "2 clashes BIM fechados": "2 BIM clashes closed",
  "Rev. B removida dos pacotes ativos": "Rev. B removed from active packages",
  "Verificar hashes finais": "Verify final hashes",
  "Confirmar plano de recuperação": "Confirm recovery plan",
  "Liberar emissão executiva": "Release executive issue",
  "Status dos pacotes": "Package status",
  "10 disciplinas notificadas": "10 disciplines notified",
  "5 responsáveis críticos marcados": "5 critical owners tagged",
  "Gate EXE-02 atualizado": "Gate EXE-02 updated",
  "Revisar texto": "Review message",
  "Confirmar audiência": "Confirm audience",
  "Publicar no canal do projeto": "Publish to project channel",
};

type MfLanguageContextValue = {
  language: MfLanguage;
  setLanguage: (language: MfLanguage) => void;
  t: (text: string) => string;
};

const MfLanguageContext = createContext<MfLanguageContextValue | null>(null);

export function MfLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<MfLanguage>("pt");

  const value = useMemo<MfLanguageContextValue>(() => ({
    language,
    setLanguage(nextLanguage) {
      setLanguageState(nextLanguage);
    },
    t(text) {
      return language === "en" ? english[text] ?? text : text;
    },
  }), [language]);

  return <MfLanguageContext.Provider value={value}>{children}</MfLanguageContext.Provider>;
}

export function useMfLanguage() {
  const context = useContext(MfLanguageContext);
  if (!context) throw new Error("useMfLanguage must be used inside MfLanguageProvider");
  return context;
}
